[phases.setup]
nixPkgs = ["python311", "gcc", "redis"]

[phases.install]
cmds = [
  "pip install --no-cache-dir --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "sh start.sh"
