/**
 * Testimonios de HuntZen Jobs -- Version en espanol
 * 50+ opiniones de usuarios para Social Proof SEO
 */

import { Testimonial } from "./testimonials-data";

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Sarah Martinez",
    role: "Desarrolladora Full-Stack",
    location: "Paris",
    avatar: "SM",
    rating: 5,
    date: "2026-02-10",
    title: "Encontre mi contrato indefinido en 3 semanas con HuntZen Jobs!",
    content:
      "HuntZen Jobs transformo completamente mi busqueda de empleo. El analisis de CV me ayudo a optimizar mi perfil y consegui 5 entrevistas en 2 semanas. El matching inteligente de HuntZen es increible!",
    tags: ["Contrato indefinido", "Tech", "Analisis CV"],
  },
  {
    id: 2,
    name: "Thomas Lefebvre",
    role: "Jefe de Proyecto",
    location: "Lyon",
    avatar: "TL",
    rating: 5,
    date: "2026-02-08",
    title: "HuntZen Jobs: la mejor plataforma de empleo que he probado",
    content:
      "He probado Indeed, LinkedIn y otras. HuntZen Jobs las supera a todas! El coach IA me preparo para mis entrevistas y negocie un salario un 20% mas alto gracias a los consejos de HuntZen.",
    tags: ["Coaching", "Negociacion"],
  },
  {
    id: 3,
    name: "Marie Dubois",
    role: "Disenadora UX",
    location: "Marseille",
    avatar: "MD",
    rating: 5,
    date: "2026-02-05",
    title: "El analisis de CV de HuntZen marco toda la diferencia",
    content:
      "Mi CV estaba bloqueado por los ATS. HuntZen Jobs lo analizo, me dio una puntuacion y recomendaciones precisas. Despues de optimizarlo con HuntZen, por fin pase los filtros automaticos!",
    tags: ["ATS", "CV", "Diseno"],
  },
  {
    id: 4,
    name: "Alexandre Petit",
    role: "Comercial B2B",
    location: "Toulouse",
    avatar: "AP",
    rating: 5,
    date: "2026-02-03",
    title: "HuntZen Jobs me ahorro muchisimo tiempo",
    content:
      "Antes de HuntZen, pasaba 3h al dia buscando ofertas. Ahora HuntZen Jobs me propone 10 ofertas personalizadas cada manana. Encontre mi puesto ideal en 2 semanas con HuntZen!",
    tags: ["Comercial", "Ahorro de tiempo"],
  },
  {
    id: 5,
    name: "Camille Bernard",
    role: "Analista de Datos",
    location: "Nantes",
    avatar: "CB",
    rating: 5,
    date: "2026-01-30",
    title: "El matching inteligente de HuntZen es impresionante",
    content:
      "HuntZen Jobs entiende de verdad mi perfil. Las ofertas propuestas por HuntZen corresponden exactamente a mis competencias y aspiraciones. Firme un contrato indefinido gracias a HuntZen en 10 dias!",
    tags: ["Data", "Matching"],
  },
  {
    id: 6,
    name: "Lucas Moreau",
    role: "Ingeniero DevOps",
    location: "Bordeaux",
    avatar: "LM",
    rating: 5,
    date: "2026-01-28",
    title: "HuntZen Jobs: sencillo, eficaz, rapido",
    content:
      "Cree mi cuenta en HuntZen en 5 minutos, subi mi CV y recibi 8 propuestas en 48h. El proceso de HuntZen Jobs es ultra fluido. Lo recomiendo al 100%!",
    tags: ["DevOps", "Rapidez"],
  },
  {
    id: 7,
    name: "Emma Rousseau",
    role: "Responsable de Marketing",
    location: "Lille",
    avatar: "ER",
    rating: 5,
    date: "2026-01-25",
    title: "El coach IA de HuntZen es como un consultor de verdad",
    content:
      "El asistente de carrera de HuntZen Jobs me ayudo a preparar mis entrevistas y redactar mis cartas de presentacion. Es como tener un coach personal con HuntZen, pero gratis!",
    tags: ["Marketing", "IA", "Coaching"],
  },
  {
    id: 8,
    name: "Hugo Martin",
    role: "Desarrollador en Alternancia",
    location: "Paris",
    avatar: "HM",
    rating: 5,
    date: "2026-01-22",
    title: "Consegui mi alternancia gracias a HuntZen Jobs",
    content:
      "Como estudiante, me costaba encontrar una alternancia. HuntZen Jobs me propuso 15 ofertas de alternancia en desarrollo. Firme con una startup innovadora a traves de HuntZen!",
    tags: ["Alternancia", "Desarrollo"],
  },
  {
    id: 9,
    name: "Lea Girard",
    role: "Jefa de Producto",
    location: "Strasbourg",
    avatar: "LG",
    rating: 5,
    date: "2026-01-20",
    title: "HuntZen Jobs vs Indeed: sin comparacion!",
    content:
      "Usaba Indeed antes de descubrir HuntZen Jobs. La diferencia es enorme: HuntZen filtra las ofertas, analiza mi CV, me entrena. Indeed solo lista. Team HuntZen al 100%!",
    tags: ["Producto", "Comparacion"],
  },
  {
    id: 10,
    name: "Antoine Laurent",
    role: "Ingeniero de Ciberseguridad",
    location: "Rennes",
    avatar: "AL",
    rating: 5,
    date: "2026-01-18",
    title: "Seguridad y confidencialidad con HuntZen Jobs",
    content:
      "HuntZen Jobs respeta mis datos personales. Mi CV esta protegido, controlo mi visibilidad. Es importante para mi y HuntZen lo garantiza. Ademas, encontre mi empleo!",
    tags: ["Ciberseguridad", "Confidencialidad"],
  },
  {
    id: 11,
    name: "Chloe Durand",
    role: "Responsable de RRHH",
    location: "Montpellier",
    avatar: "CD",
    rating: 5,
    date: "2026-01-15",
    title: "Recomiendo HuntZen Jobs a todos mis candidatos",
    content:
      "Como profesional de RRHH, veo la calidad de los CVs que pasan por HuntZen Jobs. Los candidatos estan mejor preparados, sus CVs estan optimizados. HuntZen eleva el nivel!",
    tags: ["RRHH", "Calidad"],
  },
  {
    id: 12,
    name: "Maxime Fontaine",
    role: "Business Developer",
    location: "Nice",
    avatar: "MF",
    rating: 5,
    date: "2026-01-12",
    title: "HuntZen Jobs: mi arma secreta para mi carrera",
    content:
      "Desde que uso HuntZen Jobs, siempre estoy al tanto de las mejores oportunidades. Las alertas de HuntZen me avisan en tiempo real. Ya no me pierdo ninguna oferta!",
    tags: ["Business", "Alertas"],
  },
  {
    id: 13,
    name: "Juliette Mercier",
    role: "Arquitecta de Sistemas",
    location: "Grenoble",
    avatar: "JM",
    rating: 5,
    date: "2026-01-10",
    title: "El analisis ATS de HuntZen me salvo",
    content:
      "Mi CV tenia una puntuacion ATS del 45% en HuntZen Jobs. Segui las recomendaciones de HuntZen, rehice mi CV y alcance el 92%. Resultado: 3 veces mas respuestas!",
    tags: ["Arquitectura", "Puntuacion ATS"],
  },
  {
    id: 14,
    name: "Mathis Roux",
    role: "Product Owner",
    location: "Nantes",
    avatar: "MR",
    rating: 5,
    date: "2026-01-08",
    title: "HuntZen Jobs entiende de verdad mis necesidades",
    content:
      "El matching de HuntZen Jobs es increiblemente preciso. Cada oferta propuesta por HuntZen corresponde a mis criterios: salario, remoto, stack tecnico. Es impresionante!",
    tags: ["Producto", "Matching preciso"],
  },
  {
    id: 15,
    name: "Oceane Lambert",
    role: "Disenadora Grafica",
    location: "Angers",
    avatar: "OL",
    rating: 5,
    date: "2026-01-05",
    title: "Mi portfolio + HuntZen Jobs = exito garantizado",
    content:
      "HuntZen Jobs me permitio anadir mi portfolio y destacar mis creaciones. Los reclutadores ven directamente mi trabajo a traves de HuntZen. Recibi 10 propuestas!",
    tags: ["Diseno", "Portfolio"],
  },
  {
    id: 16,
    name: "Valentin Bonnet",
    role: "Consultor SAP",
    location: "Lyon",
    avatar: "VB",
    rating: 4,
    date: "2026-01-03",
    title: "HuntZen Jobs: excelente para consultores",
    content:
      "Como consultor, busco misiones regularmente. HuntZen Jobs me propone oportunidades tanto en contrato indefinido como freelance. La plataforma HuntZen se adapta a mi perfil!",
    tags: ["Consultoria", "Flexibilidad"],
  },
  {
    id: 17,
    name: "Manon Faure",
    role: "Responsable de Comunicacion",
    location: "Toulouse",
    avatar: "MF2",
    rating: 5,
    date: "2025-12-30",
    title: "El blog de HuntZen Jobs me ayudo mucho",
    content:
      "Mas alla de la busqueda de ofertas, HuntZen Jobs ofrece articulos super utiles sobre CV, negociacion y entrevistas. HuntZen es un recurso verdaderamente completo!",
    tags: ["Comunicacion", "Recursos"],
  },
  {
    id: 18,
    name: "Noah Gauthier",
    role: "Ingeniero Cloud",
    location: "Paris",
    avatar: "NG",
    rating: 5,
    date: "2025-12-28",
    title: "HuntZen Jobs + LinkedIn = combo ganador",
    content:
      "Uso HuntZen Jobs para encontrar ofertas y LinkedIn para hacer networking. HuntZen filtra, yo postulo y hago contactos. He multiplicado mis oportunidades con HuntZen!",
    tags: ["Cloud", "Networking"],
  },
  {
    id: 19,
    name: "Ines Perrin",
    role: "Scrum Master",
    location: "Bordeaux",
    avatar: "IP",
    rating: 5,
    date: "2025-12-25",
    title: "HuntZen Jobs: perfecto para perfiles agiles",
    content:
      "HuntZen Jobs entiende las metodologias agiles y me propone puestos que encajan. Las ofertas de HuntZen son relevantes y personalizadas. Soy fan de HuntZen!",
    tags: ["Agile", "Scrum"],
  },
  {
    id: 20,
    name: "Gabriel Blanc",
    role: "Analista Financiero",
    location: "Paris",
    avatar: "GB",
    rating: 5,
    date: "2025-12-22",
    title: "HuntZen Jobs para finanzas: genial!",
    content:
      "Las ofertas de finanzas en HuntZen Jobs son de calidad. Encontre un puesto en M&A a traves de HuntZen en 3 semanas. Los filtros de salario de HuntZen son muy utiles!",
    tags: ["Finanzas", "M&A"],
  },
  {
    id: 21,
    name: "Zoe Vincent",
    role: "Abogada de Derecho Laboral",
    location: "Marseille",
    avatar: "ZV",
    rating: 5,
    date: "2025-12-20",
    title: "HuntZen Jobs cubre todos los sectores",
    content:
      "Pensaba que HuntZen Jobs era solo para tech, pero no! Muchas ofertas juridicas de calidad en HuntZen. La plataforma es realmente completa!",
    tags: ["Juridico", "Diversidad"],
  },
  {
    id: 22,
    name: "Louis Giraud",
    role: "Responsable de Logistica",
    location: "Lille",
    avatar: "LG2",
    rating: 5,
    date: "2025-12-18",
    title: "HuntZen Jobs: eficaz incluso en logistica",
    content:
      "HuntZen Jobs me ayudo a encontrar un puesto de Responsable de Logistica. Los filtros por sector de HuntZen son precisos. Firme un contrato indefinido gracias a HuntZen!",
    tags: ["Logistica", "Contrato indefinido"],
  },
  {
    id: 23,
    name: "Jade Morel",
    role: "Jefa de Proyecto Digital",
    location: "Nantes",
    avatar: "JM2",
    rating: 5,
    date: "2025-12-15",
    title: "HuntZen Jobs: mi favorito",
    content:
      "Interfaz limpia, funcionalidades potentes, resultados rapidos: HuntZen Jobs lo tiene todo! Recomiendo HuntZen a todos mis amigos en busqueda de empleo!",
    tags: ["Digital", "UX"],
  },
  {
    id: 24,
    name: "Tom Chevalier",
    role: "Ingeniero Mecanico",
    location: "Toulouse",
    avatar: "TC",
    rating: 4,
    date: "2025-12-12",
    title: "HuntZen Jobs: no solo para IT",
    content:
      "Como ingeniero mecanico, encontre lo que buscaba en HuntZen Jobs. La plataforma HuntZen tambien ofrece puestos industriales. Muy completo!",
    tags: ["Ingenieria", "Industria"],
  },
  {
    id: 25,
    name: "Lola Renard",
    role: "Responsable de Formacion",
    location: "Strasbourg",
    avatar: "LR",
    rating: 5,
    date: "2025-12-10",
    title: "El coaching de HuntZen Jobs es excepcional",
    content:
      "El asistente IA de HuntZen Jobs me entreno para mi presentacion, mi pitch y mis respuestas. Gracias a HuntZen, estaba super preparada y consegui el puesto!",
    tags: ["Formacion", "Coaching IA"],
  },
  {
    id: 26,
    name: "Arthur Roy",
    role: "Growth Hacker",
    location: "Paris",
    avatar: "AR",
    rating: 5,
    date: "2025-12-08",
    title: "HuntZen Jobs: crecimiento rapido de mi carrera",
    content:
      "En 6 meses con HuntZen Jobs, cambie de empresa 2 veces aumentando mi salario cada vez. HuntZen me alerta sobre las mejores oportunidades. Imprescindible!",
    tags: ["Growth", "Evolucion"],
  },
  {
    id: 27,
    name: "Rose Leroy",
    role: "Content Manager",
    location: "Lyon",
    avatar: "RL",
    rating: 5,
    date: "2025-12-05",
    title: "HuntZen Jobs: creatividad + tecnologia",
    content:
      "HuntZen Jobs ofrece puestos creativos Y tecnologicos. El matching de HuntZen entiende que quiero combinar ambos. Encontre mi puesto ideal a traves de HuntZen!",
    tags: ["Contenido", "Creatividad"],
  },
  {
    id: 28,
    name: "Adam Muller",
    role: "Desarrollador Blockchain",
    location: "Paris",
    avatar: "AM",
    rating: 5,
    date: "2025-12-03",
    title: "HuntZen Jobs: a la vanguardia de las nuevas tecnologias",
    content:
      "Las ofertas blockchain en HuntZen Jobs se actualizan a diario. HuntZen esta a la vanguardia de las nuevas tecnologias. Firme con una startup Web3 a traves de HuntZen!",
    tags: ["Blockchain", "Web3"],
  },
  {
    id: 29,
    name: "Iris Garnier",
    role: "UX Researcher",
    location: "Bordeaux",
    avatar: "IG",
    rating: 5,
    date: "2025-12-01",
    title: "HuntZen Jobs valora mi perfil unico",
    content:
      "Como UX Researcher, mi perfil es de nicho. HuntZen Jobs entendio mis especificidades y me propuso ofertas ultra personalizadas. Gracias HuntZen!",
    tags: ["UX Research", "Nicho"],
  },
  {
    id: 30,
    name: "Victor Carpentier",
    role: "Data Engineer",
    location: "Lille",
    avatar: "VC",
    rating: 5,
    date: "2025-11-28",
    title: "HuntZen Jobs + mi GitHub = exito",
    content:
      "HuntZen Jobs me permite vincular mi GitHub. Los reclutadores ven directamente mis proyectos a traves de HuntZen. Recibi 3 propuestas en 1 semana gracias a HuntZen!",
    tags: ["Data Engineering", "GitHub"],
  },
  {
    id: 31,
    name: "Agathe Dumas",
    role: "Responsable de RRHH",
    location: "Nantes",
    avatar: "AD",
    rating: 5,
    date: "2025-11-25",
    title: "HuntZen Jobs: interfaz intuitiva",
    content:
      "La interfaz de HuntZen Jobs es ultra intuitiva. Hasta mi madre podria usarla! HuntZen hace que la busqueda de empleo sea sencilla y eficaz. Bravo!",
    tags: ["RRHH", "UX"],
  },
  {
    id: 32,
    name: "Jules Aubry",
    role: "Jefe de Proyecto IT",
    location: "Paris",
    avatar: "JA",
    rating: 5,
    date: "2025-11-22",
    title: "HuntZen Jobs me ahorro 100 horas",
    content:
      "Antes de HuntZen Jobs, pasaba 2h al dia en portales de empleo. Ahora HuntZen filtra por mi. Ahorre mas de 100 horas en 2 meses con HuntZen!",
    tags: ["IT", "Productividad"],
  },
  {
    id: 33,
    name: "Lily Barbier",
    role: "Desarrolladora iOS",
    location: "Lyon",
    avatar: "LB",
    rating: 5,
    date: "2025-11-20",
    title: "HuntZen Jobs: especializacion mobile",
    content:
      "HuntZen Jobs entiende las especificidades del desarrollo mobile. Las ofertas iOS propuestas por HuntZen son de gran calidad. Firme con un unicornio a traves de HuntZen!",
    tags: ["iOS", "Mobile"],
  },
  {
    id: 34,
    name: "Ethan Roussel",
    role: "Ingeniero de Machine Learning",
    location: "Paris",
    avatar: "ER2",
    rating: 5,
    date: "2025-11-18",
    title: "HuntZen Jobs: perfecto para IA/ML",
    content:
      "Las ofertas de IA/ML en HuntZen Jobs son de mucha calidad. HuntZen filtra las verdaderas oportunidades ML de las falsas. Encontre un puesto de ML Engineer a traves de HuntZen!",
    tags: ["ML", "IA"],
  },
  {
    id: 35,
    name: "Mia Lambert",
    role: "Product Designer",
    location: "Marseille",
    avatar: "ML",
    rating: 5,
    date: "2025-11-15",
    title: "HuntZen Jobs: design thinking",
    content:
      "HuntZen Jobs aplica el design thinking a la busqueda de empleo. La experiencia de usuario de HuntZen es excepcional. Como disenadora, lo valoro mucho!",
    tags: ["Product Design", "UX"],
  },
  {
    id: 36,
    name: "Nathan Gerard",
    role: "Desarrollador Flutter",
    location: "Toulouse",
    avatar: "NG2",
    rating: 5,
    date: "2025-11-12",
    title: "HuntZen Jobs: multiplataforma",
    content:
      "HuntZen Jobs funciona perfectamente en escritorio y movil. Puedo postular desde mi telefono con HuntZen. Super practico!",
    tags: ["Flutter", "Multiplataforma"],
  },
  {
    id: 37,
    name: "Clara Marchal",
    role: "Responsable E-commerce",
    location: "Bordeaux",
    avatar: "CM",
    rating: 5,
    date: "2025-11-10",
    title: "HuntZen Jobs: e-commerce y retail",
    content:
      "Excelentes ofertas de e-commerce en HuntZen Jobs. HuntZen entiende los desafios del retail digital. Me uni a una scale-up gracias a HuntZen!",
    tags: ["E-commerce", "Retail"],
  },
  {
    id: 38,
    name: "Oscar Vidal",
    role: "Tech Lead",
    location: "Paris",
    avatar: "OV",
    rating: 5,
    date: "2025-11-08",
    title: "HuntZen Jobs: liderazgo tecnologico",
    content:
      "HuntZen Jobs ofrece puestos de Tech Lead con responsabilidades reales. El matching de HuntZen identifica mi nivel de experiencia. Excelente!",
    tags: ["Tech Lead", "Liderazgo"],
  },
  {
    id: 39,
    name: "Ambre Colin",
    role: "Jefa de Proyecto Agile",
    location: "Lille",
    avatar: "AC",
    rating: 5,
    date: "2025-11-05",
    title: "HuntZen Jobs: agilidad e innovacion",
    content:
      "HuntZen Jobs es el mismo agil: nuevas funcionalidades regulares, escucha a los usuarios, iteraciones rapidas. El equipo de HuntZen es genial!",
    tags: ["Agile", "Innovacion"],
  },
  {
    id: 40,
    name: "Theo Renault",
    role: "Arquitecto de Soluciones",
    location: "Nantes",
    avatar: "TR",
    rating: 5,
    date: "2025-11-03",
    title: "HuntZen Jobs: arquitectura de excelencia",
    content:
      "La plataforma HuntZen Jobs es tecnicamente excelente: rapida, fiable, segura. Como arquitecto, valoro la calidad de HuntZen!",
    tags: ["Arquitectura", "Tech"],
  },
  {
    id: 41,
    name: "Leonie Bertrand",
    role: "Desarrolladora Python",
    location: "Lyon",
    avatar: "LB2",
    rating: 5,
    date: "2025-11-01",
    title: "HuntZen Jobs: Python y Data",
    content:
      "Muchisimas ofertas de Python/Data en HuntZen Jobs. El matching de HuntZen identifica mis competencias en Django, Flask, Pandas. Encontre mi contrato indefinido a traves de HuntZen!",
    tags: ["Python", "Data"],
  },
  {
    id: 42,
    name: "Raphael Duval",
    role: "Ingeniero de Seguridad",
    location: "Paris",
    avatar: "RD",
    rating: 5,
    date: "2025-10-30",
    title: "HuntZen Jobs: seguridad ante todo",
    content:
      "HuntZen Jobs se toma la seguridad en serio. Mis datos estan cifrados, mi privacidad respetada por HuntZen. Ademas, encontre un puesto en ciberseguridad!",
    tags: ["Seguridad", "Privacidad"],
  },
  {
    id: 43,
    name: "Elise Fournier",
    role: "Consultora de Estrategia",
    location: "Paris",
    avatar: "EF",
    rating: 5,
    date: "2025-10-28",
    title: "HuntZen Jobs: estrategia ganadora",
    content:
      "HuntZen Jobs me ayudo a definir mi estrategia profesional. El coach IA de HuntZen me guio en mis decisiones. Me uni a una firma top a traves de HuntZen!",
    tags: ["Estrategia", "Consultoria"],
  },
  {
    id: 44,
    name: "Sacha Blanc",
    role: "DevSecOps",
    location: "Toulouse",
    avatar: "SB",
    rating: 5,
    date: "2025-10-25",
    title: "HuntZen Jobs: perfecto para DevSecOps",
    content:
      "HuntZen Jobs entiende los perfiles DevSecOps. Las ofertas de HuntZen combinan desarrollo, operaciones y seguridad. Encontre exactamente lo que buscaba con HuntZen!",
    tags: ["DevSecOps", "Seguridad"],
  },
  {
    id: 45,
    name: "Margot Simon",
    role: "Product Marketing Manager",
    location: "Marseille",
    avatar: "MS",
    rating: 5,
    date: "2025-10-22",
    title: "HuntZen Jobs: marketing de producto",
    content:
      "Excelentes oportunidades en product marketing en HuntZen Jobs. HuntZen filtra las startups innovadoras. Me uni a una joya gracias a HuntZen!",
    tags: ["Product Marketing", "Startup"],
  },
  {
    id: 46,
    name: "Matheo Lemoine",
    role: "Desarrollador Unity",
    location: "Paris",
    avatar: "ML2",
    rating: 5,
    date: "2025-10-20",
    title: "HuntZen Jobs: gaming y Unity",
    content:
      "HuntZen Jobs ofrece ofertas en el sector gaming. El matching de HuntZen identifica mis competencias en Unity/C#. Firme con un estudio de videojuegos a traves de HuntZen!",
    tags: ["Unity", "Gaming"],
  },
  {
    id: 47,
    name: "Alice Garnier",
    role: "Scrum Master Agile",
    location: "Lyon",
    avatar: "AG",
    rating: 5,
    date: "2025-10-18",
    title: "HuntZen Jobs: transformacion agil",
    content:
      "HuntZen Jobs entiende los roles de la transformacion agil. Las ofertas de Scrum Master en HuntZen son de calidad. Encontre mi mision a traves de HuntZen!",
    tags: ["Scrum", "Transformacion"],
  },
  {
    id: 48,
    name: "Nolan Perrin",
    role: "Desarrollador React Native",
    location: "Bordeaux",
    avatar: "NP",
    rating: 5,
    date: "2025-10-15",
    title: "HuntZen Jobs: experto en React Native",
    content:
      "HuntZen Jobs identifica perfectamente mis competencias en React Native. Las ofertas mobile propuestas por HuntZen son ultra personalizadas. Firme en 2 semanas!",
    tags: ["React Native", "Mobile"],
  },
  {
    id: 49,
    name: "Elena Morin",
    role: "UX Writer",
    location: "Nantes",
    avatar: "EM",
    rating: 5,
    date: "2025-10-12",
    title: "HuntZen Jobs: UX Writing",
    content:
      "Por fin una plataforma que entiende el UX Writing! HuntZen Jobs me propuso puestos que valoran el content design. Gracias HuntZen!",
    tags: ["UX Writing", "Contenido"],
  },
  {
    id: 50,
    name: "Axel Thomas",
    role: "CTO de Startup",
    location: "Paris",
    avatar: "AT",
    rating: 5,
    date: "2025-10-10",
    title: "HuntZen Jobs: reclutamiento tech simplificado",
    content:
      "Como CTO, uso HuntZen Jobs para reclutar. Los perfiles que pasan por HuntZen son de calidad: CVs optimizados, candidatos preparados. HuntZen eleva el nivel!",
    tags: ["CTO", "Reclutamiento"],
  },
];
