/**
 * Depoimentos do HuntZen Jobs -- Versao em portugues
 * 50+ avaliacoes de usuarios para Social Proof SEO
 */

import { Testimonial } from "./testimonials-data";

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Sarah Martinez",
    role: "Desenvolvedora Full-Stack",
    location: "Paris",
    avatar: "SM",
    rating: 5,
    date: "2026-02-10",
    title: "Encontrei meu contrato efetivo em 3 semanas com o HuntZen Jobs!",
    content:
      "O HuntZen Jobs transformou completamente minha busca de emprego. A analise de CV me ajudou a otimizar meu perfil e consegui 5 entrevistas em 2 semanas. O matching inteligente do HuntZen e incrivel!",
    tags: ["Contrato efetivo", "Tech", "Analise de CV"],
  },
  {
    id: 2,
    name: "Thomas Lefebvre",
    role: "Gerente de Projetos",
    location: "Lyon",
    avatar: "TL",
    rating: 5,
    date: "2026-02-08",
    title: "HuntZen Jobs: a melhor plataforma de emprego que ja testei",
    content:
      "Ja testei Indeed, LinkedIn e outras. O HuntZen Jobs supera todas! O coach IA me preparou para minhas entrevistas e negociei um salario 20% maior gracas aos conselhos do HuntZen.",
    tags: ["Coaching", "Negociacao"],
  },
  {
    id: 3,
    name: "Marie Dubois",
    role: "Designer UX",
    location: "Marseille",
    avatar: "MD",
    rating: 5,
    date: "2026-02-05",
    title: "A analise de CV do HuntZen fez toda a diferenca",
    content:
      "Meu CV estava bloqueado pelos ATS. O HuntZen Jobs analisou, me deu uma pontuacao e recomendacoes precisas. Apos otimizar com o HuntZen, finalmente passei nos filtros automaticos!",
    tags: ["ATS", "CV", "Design"],
  },
  {
    id: 4,
    name: "Alexandre Petit",
    role: "Comercial B2B",
    location: "Toulouse",
    avatar: "AP",
    rating: 5,
    date: "2026-02-03",
    title: "O HuntZen Jobs me economizou muito tempo",
    content:
      "Antes do HuntZen, eu passava 3h por dia procurando vagas. Agora o HuntZen Jobs me propoe 10 vagas personalizadas todas as manhas. Encontrei minha posicao ideal em 2 semanas com o HuntZen!",
    tags: ["Comercial", "Economia de tempo"],
  },
  {
    id: 5,
    name: "Camille Bernard",
    role: "Analista de Dados",
    location: "Nantes",
    avatar: "CB",
    rating: 5,
    date: "2026-01-30",
    title: "O matching inteligente do HuntZen e impressionante",
    content:
      "O HuntZen Jobs realmente entende meu perfil. As vagas propostas pelo HuntZen correspondem exatamente as minhas competencias e aspiracoes. Assinei um contrato efetivo gracas ao HuntZen em 10 dias!",
    tags: ["Data", "Matching"],
  },
  {
    id: 6,
    name: "Lucas Moreau",
    role: "Engenheiro DevOps",
    location: "Bordeaux",
    avatar: "LM",
    rating: 5,
    date: "2026-01-28",
    title: "HuntZen Jobs: simples, eficaz, rapido",
    content:
      "Criei minha conta no HuntZen em 5 minutos, fiz upload do meu CV e recebi 8 propostas em 48h. O processo do HuntZen Jobs e ultra fluido. Recomendo 100%!",
    tags: ["DevOps", "Rapidez"],
  },
  {
    id: 7,
    name: "Emma Rousseau",
    role: "Gerente de Marketing",
    location: "Lille",
    avatar: "ER",
    rating: 5,
    date: "2026-01-25",
    title: "O coach IA do HuntZen e como um consultor de verdade",
    content:
      "O assistente de carreira do HuntZen Jobs me ajudou a preparar minhas entrevistas e redigir minhas cartas de apresentacao. E como ter um coach pessoal com o HuntZen, so que gratis!",
    tags: ["Marketing", "IA", "Coaching"],
  },
  {
    id: 8,
    name: "Hugo Martin",
    role: "Desenvolvedor em Alternancia",
    location: "Paris",
    avatar: "HM",
    rating: 5,
    date: "2026-01-22",
    title: "Consegui meu estagio gracas ao HuntZen Jobs",
    content:
      "Como estudante, estava com dificuldade para encontrar uma alternancia. O HuntZen Jobs me sugeriu 15 vagas de alternancia em desenvolvimento. Assinei com uma startup inovadora pelo HuntZen!",
    tags: ["Alternancia", "Desenvolvimento"],
  },
  {
    id: 9,
    name: "Lea Girard",
    role: "Gerente de Produto",
    location: "Strasbourg",
    avatar: "LG",
    rating: 5,
    date: "2026-01-20",
    title: "HuntZen Jobs vs Indeed: sem comparacao!",
    content:
      "Eu usava o Indeed antes de descobrir o HuntZen Jobs. A diferenca e enorme: o HuntZen filtra as vagas, analisa meu CV, me treina. O Indeed so lista. Time HuntZen 100%!",
    tags: ["Produto", "Comparacao"],
  },
  {
    id: 10,
    name: "Antoine Laurent",
    role: "Engenheiro de Ciberseguranca",
    location: "Rennes",
    avatar: "AL",
    rating: 5,
    date: "2026-01-18",
    title: "Seguranca e confidencialidade com o HuntZen Jobs",
    content:
      "O HuntZen Jobs respeita meus dados pessoais. Meu CV esta protegido, controlo minha visibilidade. E importante para mim e o HuntZen garante isso. Alem disso, encontrei meu emprego!",
    tags: ["Ciberseguranca", "Confidencialidade"],
  },
  {
    id: 11,
    name: "Chloe Durand",
    role: "Gerente de RH",
    location: "Montpellier",
    avatar: "CD",
    rating: 5,
    date: "2026-01-15",
    title: "Recomendo o HuntZen Jobs a todos os meus candidatos",
    content:
      "Como profissional de RH, vejo a qualidade dos CVs que passam pelo HuntZen Jobs. Os candidatos estao mais bem preparados, seus CVs estao otimizados. O HuntZen eleva o nivel!",
    tags: ["RH", "Qualidade"],
  },
  {
    id: 12,
    name: "Maxime Fontaine",
    role: "Business Developer",
    location: "Nice",
    avatar: "MF",
    rating: 5,
    date: "2026-01-12",
    title: "HuntZen Jobs: minha arma secreta para minha carreira",
    content:
      "Desde que uso o HuntZen Jobs, estou sempre por dentro das melhores oportunidades. Os alertas do HuntZen me avisam em tempo real. Nao perco mais nenhuma vaga!",
    tags: ["Business", "Alertas"],
  },
  {
    id: 13,
    name: "Juliette Mercier",
    role: "Arquiteta de Sistemas",
    location: "Grenoble",
    avatar: "JM",
    rating: 5,
    date: "2026-01-10",
    title: "A analise ATS do HuntZen me salvou",
    content:
      "Meu CV tinha uma pontuacao ATS de 45% no HuntZen Jobs. Segui as recomendacoes do HuntZen, refiz meu CV e atingi 92%. Resultado: 3 vezes mais respostas!",
    tags: ["Arquitetura", "Pontuacao ATS"],
  },
  {
    id: 14,
    name: "Mathis Roux",
    role: "Product Owner",
    location: "Nantes",
    avatar: "MR",
    rating: 5,
    date: "2026-01-08",
    title: "O HuntZen Jobs realmente entende minhas necessidades",
    content:
      "O matching do HuntZen Jobs e incrivelmente preciso. Cada vaga proposta pelo HuntZen corresponde aos meus criterios: salario, remoto, stack tecnico. E impressionante!",
    tags: ["Produto", "Matching preciso"],
  },
  {
    id: 15,
    name: "Oceane Lambert",
    role: "Designer Grafica",
    location: "Angers",
    avatar: "OL",
    rating: 5,
    date: "2026-01-05",
    title: "Meu portfolio + HuntZen Jobs = sucesso garantido",
    content:
      "O HuntZen Jobs me permitiu adicionar meu portfolio e destacar minhas criacoes. Os recrutadores veem diretamente meu trabalho pelo HuntZen. Recebi 10 propostas!",
    tags: ["Design", "Portfolio"],
  },
  {
    id: 16,
    name: "Valentin Bonnet",
    role: "Consultor SAP",
    location: "Lyon",
    avatar: "VB",
    rating: 4,
    date: "2026-01-03",
    title: "HuntZen Jobs: excelente para consultores",
    content:
      "Como consultor, busco missoes regularmente. O HuntZen Jobs me propoe oportunidades tanto em contrato efetivo quanto freelance. A plataforma HuntZen se adapta ao meu perfil!",
    tags: ["Consultoria", "Flexibilidade"],
  },
  {
    id: 17,
    name: "Manon Faure",
    role: "Responsavel de Comunicacao",
    location: "Toulouse",
    avatar: "MF2",
    rating: 5,
    date: "2025-12-30",
    title: "O blog do HuntZen Jobs me ajudou muito",
    content:
      "Alem da busca de vagas, o HuntZen Jobs oferece artigos super uteis sobre CV, negociacao e entrevistas. O HuntZen e um recurso verdadeiramente completo!",
    tags: ["Comunicacao", "Recursos"],
  },
  {
    id: 18,
    name: "Noah Gauthier",
    role: "Engenheiro Cloud",
    location: "Paris",
    avatar: "NG",
    rating: 5,
    date: "2025-12-28",
    title: "HuntZen Jobs + LinkedIn = combo vencedor",
    content:
      "Uso o HuntZen Jobs para encontrar vagas e o LinkedIn para networking. O HuntZen filtra, eu me candidato e faco contatos. Multipliquei minhas oportunidades com o HuntZen!",
    tags: ["Cloud", "Networking"],
  },
  {
    id: 19,
    name: "Ines Perrin",
    role: "Scrum Master",
    location: "Bordeaux",
    avatar: "IP",
    rating: 5,
    date: "2025-12-25",
    title: "HuntZen Jobs: perfeito para perfis ageis",
    content:
      "O HuntZen Jobs entende as metodologias ageis e me propoe posicoes que combinam. As vagas do HuntZen sao relevantes e personalizadas. Sou fa do HuntZen!",
    tags: ["Agile", "Scrum"],
  },
  {
    id: 20,
    name: "Gabriel Blanc",
    role: "Analista Financeiro",
    location: "Paris",
    avatar: "GB",
    rating: 5,
    date: "2025-12-22",
    title: "HuntZen Jobs para financas: otimo!",
    content:
      "As vagas de financas no HuntZen Jobs sao de qualidade. Encontrei uma posicao em M&A pelo HuntZen em 3 semanas. Os filtros de salario do HuntZen sao muito uteis!",
    tags: ["Financas", "M&A"],
  },
  {
    id: 21,
    name: "Zoe Vincent",
    role: "Advogada de Direito do Trabalho",
    location: "Marseille",
    avatar: "ZV",
    rating: 5,
    date: "2025-12-20",
    title: "O HuntZen Jobs cobre todos os setores",
    content:
      "Achava que o HuntZen Jobs era so para tech, mas nao! Muitas vagas juridicas de qualidade no HuntZen. A plataforma e realmente completa!",
    tags: ["Juridico", "Diversidade"],
  },
  {
    id: 22,
    name: "Louis Giraud",
    role: "Gerente de Logistica",
    location: "Lille",
    avatar: "LG2",
    rating: 5,
    date: "2025-12-18",
    title: "HuntZen Jobs: eficaz ate na logistica",
    content:
      "O HuntZen Jobs me ajudou a encontrar uma posicao de Gerente de Logistica. Os filtros por setor do HuntZen sao precisos. Assinei um contrato efetivo gracas ao HuntZen!",
    tags: ["Logistica", "Contrato efetivo"],
  },
  {
    id: 23,
    name: "Jade Morel",
    role: "Gerente de Projeto Digital",
    location: "Nantes",
    avatar: "JM2",
    rating: 5,
    date: "2025-12-15",
    title: "HuntZen Jobs: meu favorito",
    content:
      "Interface limpa, funcionalidades poderosas, resultados rapidos: o HuntZen Jobs acerta em tudo! Recomendo o HuntZen a todos os meus amigos em busca de emprego!",
    tags: ["Digital", "UX"],
  },
  {
    id: 24,
    name: "Tom Chevalier",
    role: "Engenheiro Mecanico",
    location: "Toulouse",
    avatar: "TC",
    rating: 4,
    date: "2025-12-12",
    title: "HuntZen Jobs: nao e so para TI",
    content:
      "Como engenheiro mecanico, encontrei o que procurava no HuntZen Jobs. A plataforma HuntZen tambem oferece vagas industriais. Muito completo!",
    tags: ["Engenharia", "Industria"],
  },
  {
    id: 25,
    name: "Lola Renard",
    role: "Gerente de Treinamento",
    location: "Strasbourg",
    avatar: "LR",
    rating: 5,
    date: "2025-12-10",
    title: "O coaching do HuntZen Jobs e excepcional",
    content:
      "O assistente IA do HuntZen Jobs me treinou na minha apresentacao, no meu pitch e nas minhas respostas. Gracas ao HuntZen, estava super preparada e consegui a vaga!",
    tags: ["Treinamento", "Coaching IA"],
  },
  {
    id: 26,
    name: "Arthur Roy",
    role: "Growth Hacker",
    location: "Paris",
    avatar: "AR",
    rating: 5,
    date: "2025-12-08",
    title: "HuntZen Jobs: crescimento rapido da minha carreira",
    content:
      "Em 6 meses com o HuntZen Jobs, mudei de empresa 2 vezes aumentando meu salario a cada vez. O HuntZen me alerta sobre as melhores oportunidades. Indispensavel!",
    tags: ["Growth", "Evolucao"],
  },
  {
    id: 27,
    name: "Rose Leroy",
    role: "Content Manager",
    location: "Lyon",
    avatar: "RL",
    rating: 5,
    date: "2025-12-05",
    title: "HuntZen Jobs: criatividade + tecnologia",
    content:
      "O HuntZen Jobs oferece vagas criativas E tecnologicas. O matching do HuntZen entende que quero combinar os dois. Encontrei minha posicao ideal pelo HuntZen!",
    tags: ["Conteudo", "Criatividade"],
  },
  {
    id: 28,
    name: "Adam Muller",
    role: "Desenvolvedor Blockchain",
    location: "Paris",
    avatar: "AM",
    rating: 5,
    date: "2025-12-03",
    title: "HuntZen Jobs: na vanguarda das novas tecnologias",
    content:
      "As vagas de blockchain no HuntZen Jobs sao atualizadas diariamente. O HuntZen esta na vanguarda das novas tecnologias. Assinei com uma startup Web3 pelo HuntZen!",
    tags: ["Blockchain", "Web3"],
  },
  {
    id: 29,
    name: "Iris Garnier",
    role: "UX Researcher",
    location: "Bordeaux",
    avatar: "IG",
    rating: 5,
    date: "2025-12-01",
    title: "O HuntZen Jobs valoriza meu perfil unico",
    content:
      "Como UX Researcher, meu perfil e de nicho. O HuntZen Jobs entendeu minhas especificidades e me sugeriu vagas ultra personalizadas. Obrigada HuntZen!",
    tags: ["UX Research", "Nicho"],
  },
  {
    id: 30,
    name: "Victor Carpentier",
    role: "Data Engineer",
    location: "Lille",
    avatar: "VC",
    rating: 5,
    date: "2025-11-28",
    title: "HuntZen Jobs + meu GitHub = sucesso",
    content:
      "O HuntZen Jobs me permite vincular meu GitHub. Os recrutadores veem diretamente meus projetos pelo HuntZen. Recebi 3 propostas em 1 semana gracas ao HuntZen!",
    tags: ["Data Engineering", "GitHub"],
  },
  {
    id: 31,
    name: "Agathe Dumas",
    role: "Responsavel de RH",
    location: "Nantes",
    avatar: "AD",
    rating: 5,
    date: "2025-11-25",
    title: "HuntZen Jobs: interface intuitiva",
    content:
      "A interface do HuntZen Jobs e ultra intuitiva. Ate minha mae poderia usar! O HuntZen torna a busca de emprego simples e eficaz. Parabens!",
    tags: ["RH", "UX"],
  },
  {
    id: 32,
    name: "Jules Aubry",
    role: "Gerente de Projeto TI",
    location: "Paris",
    avatar: "JA",
    rating: 5,
    date: "2025-11-22",
    title: "O HuntZen Jobs me economizou 100 horas",
    content:
      "Antes do HuntZen Jobs, eu passava 2h por dia em sites de emprego. Agora o HuntZen filtra para mim. Economizei mais de 100 horas em 2 meses com o HuntZen!",
    tags: ["TI", "Produtividade"],
  },
  {
    id: 33,
    name: "Lily Barbier",
    role: "Desenvolvedora iOS",
    location: "Lyon",
    avatar: "LB",
    rating: 5,
    date: "2025-11-20",
    title: "HuntZen Jobs: especializacao mobile",
    content:
      "O HuntZen Jobs entende as especificidades do desenvolvimento mobile. As vagas iOS propostas pelo HuntZen sao de grande qualidade. Assinei com um unicornio pelo HuntZen!",
    tags: ["iOS", "Mobile"],
  },
  {
    id: 34,
    name: "Ethan Roussel",
    role: "Engenheiro de Machine Learning",
    location: "Paris",
    avatar: "ER2",
    rating: 5,
    date: "2025-11-18",
    title: "HuntZen Jobs: perfeito para IA/ML",
    content:
      "As vagas de IA/ML no HuntZen Jobs sao de muita qualidade. O HuntZen filtra as verdadeiras oportunidades ML das falsas. Encontrei uma posicao de ML Engineer pelo HuntZen!",
    tags: ["ML", "IA"],
  },
  {
    id: 35,
    name: "Mia Lambert",
    role: "Product Designer",
    location: "Marseille",
    avatar: "ML",
    rating: 5,
    date: "2025-11-15",
    title: "HuntZen Jobs: design thinking",
    content:
      "O HuntZen Jobs aplica o design thinking a busca de emprego. A experiencia do usuario do HuntZen e excepcional. Como designer, eu valorizo muito!",
    tags: ["Product Design", "UX"],
  },
  {
    id: 36,
    name: "Nathan Gerard",
    role: "Desenvolvedor Flutter",
    location: "Toulouse",
    avatar: "NG2",
    rating: 5,
    date: "2025-11-12",
    title: "HuntZen Jobs: multiplataforma",
    content:
      "O HuntZen Jobs funciona perfeitamente no desktop e no celular. Posso me candidatar pelo meu telefone com o HuntZen. Super pratico!",
    tags: ["Flutter", "Multiplataforma"],
  },
  {
    id: 37,
    name: "Clara Marchal",
    role: "Gerente de E-commerce",
    location: "Bordeaux",
    avatar: "CM",
    rating: 5,
    date: "2025-11-10",
    title: "HuntZen Jobs: e-commerce e varejo",
    content:
      "Excelentes vagas de e-commerce no HuntZen Jobs. O HuntZen entende os desafios do varejo digital. Entrei para uma scale-up gracas ao HuntZen!",
    tags: ["E-commerce", "Varejo"],
  },
  {
    id: 38,
    name: "Oscar Vidal",
    role: "Tech Lead",
    location: "Paris",
    avatar: "OV",
    rating: 5,
    date: "2025-11-08",
    title: "HuntZen Jobs: lideranca tecnologica",
    content:
      "O HuntZen Jobs oferece vagas de Tech Lead com responsabilidades reais. O matching do HuntZen identifica meu nivel de experiencia. Excelente!",
    tags: ["Tech Lead", "Lideranca"],
  },
  {
    id: 39,
    name: "Ambre Colin",
    role: "Gerente de Projeto Agile",
    location: "Lille",
    avatar: "AC",
    rating: 5,
    date: "2025-11-05",
    title: "HuntZen Jobs: agilidade e inovacao",
    content:
      "O HuntZen Jobs e ele mesmo agil: funcionalidades regulares, escuta dos usuarios, iteracoes rapidas. A equipe do HuntZen e otima!",
    tags: ["Agile", "Inovacao"],
  },
  {
    id: 40,
    name: "Theo Renault",
    role: "Arquiteto de Solucoes",
    location: "Nantes",
    avatar: "TR",
    rating: 5,
    date: "2025-11-03",
    title: "HuntZen Jobs: arquitetura de excelencia",
    content:
      "A plataforma HuntZen Jobs e tecnicamente excelente: rapida, confiavel, segura. Como arquiteto, valorizo a qualidade do HuntZen!",
    tags: ["Arquitetura", "Tech"],
  },
  {
    id: 41,
    name: "Leonie Bertrand",
    role: "Desenvolvedora Python",
    location: "Lyon",
    avatar: "LB2",
    rating: 5,
    date: "2025-11-01",
    title: "HuntZen Jobs: Python e Data",
    content:
      "Muitissimas vagas de Python/Data no HuntZen Jobs. O matching do HuntZen identifica minhas competencias em Django, Flask, Pandas. Encontrei meu contrato efetivo pelo HuntZen!",
    tags: ["Python", "Data"],
  },
  {
    id: 42,
    name: "Raphael Duval",
    role: "Engenheiro de Seguranca",
    location: "Paris",
    avatar: "RD",
    rating: 5,
    date: "2025-10-30",
    title: "HuntZen Jobs: seguranca em primeiro lugar",
    content:
      "O HuntZen Jobs leva a seguranca a serio. Meus dados estao criptografados, minha privacidade e respeitada pelo HuntZen. Alem disso, encontrei uma vaga em ciberseguranca!",
    tags: ["Seguranca", "Privacidade"],
  },
  {
    id: 43,
    name: "Elise Fournier",
    role: "Consultora de Estrategia",
    location: "Paris",
    avatar: "EF",
    rating: 5,
    date: "2025-10-28",
    title: "HuntZen Jobs: estrategia vencedora",
    content:
      "O HuntZen Jobs me ajudou a definir minha estrategia de carreira. O coach IA do HuntZen me guiou nas minhas escolhas. Entrei para uma firma top pelo HuntZen!",
    tags: ["Estrategia", "Consultoria"],
  },
  {
    id: 44,
    name: "Sacha Blanc",
    role: "DevSecOps",
    location: "Toulouse",
    avatar: "SB",
    rating: 5,
    date: "2025-10-25",
    title: "HuntZen Jobs: perfeito para DevSecOps",
    content:
      "O HuntZen Jobs entende os perfis DevSecOps. As vagas do HuntZen combinam desenvolvimento, operacoes e seguranca. Encontrei exatamente o que procurava com o HuntZen!",
    tags: ["DevSecOps", "Seguranca"],
  },
  {
    id: 45,
    name: "Margot Simon",
    role: "Product Marketing Manager",
    location: "Marseille",
    avatar: "MS",
    rating: 5,
    date: "2025-10-22",
    title: "HuntZen Jobs: marketing de produto",
    content:
      "Excelentes oportunidades de product marketing no HuntZen Jobs. O HuntZen filtra as startups inovadoras. Entrei para uma joia gracas ao HuntZen!",
    tags: ["Product Marketing", "Startup"],
  },
  {
    id: 46,
    name: "Matheo Lemoine",
    role: "Desenvolvedor Unity",
    location: "Paris",
    avatar: "ML2",
    rating: 5,
    date: "2025-10-20",
    title: "HuntZen Jobs: gaming e Unity",
    content:
      "O HuntZen Jobs oferece vagas no setor de gaming. O matching do HuntZen identifica minhas competencias em Unity/C#. Assinei com um estudio de jogos pelo HuntZen!",
    tags: ["Unity", "Gaming"],
  },
  {
    id: 47,
    name: "Alice Garnier",
    role: "Scrum Master Agile",
    location: "Lyon",
    avatar: "AG",
    rating: 5,
    date: "2025-10-18",
    title: "HuntZen Jobs: transformacao agil",
    content:
      "O HuntZen Jobs entende os papeis da transformacao agil. As vagas de Scrum Master no HuntZen sao de qualidade. Encontrei minha missao pelo HuntZen!",
    tags: ["Scrum", "Transformacao"],
  },
  {
    id: 48,
    name: "Nolan Perrin",
    role: "Desenvolvedor React Native",
    location: "Bordeaux",
    avatar: "NP",
    rating: 5,
    date: "2025-10-15",
    title: "HuntZen Jobs: especialista em React Native",
    content:
      "O HuntZen Jobs identifica perfeitamente minhas competencias em React Native. As vagas mobile propostas pelo HuntZen sao ultra personalizadas. Assinei em 2 semanas!",
    tags: ["React Native", "Mobile"],
  },
  {
    id: 49,
    name: "Elena Morin",
    role: "UX Writer",
    location: "Nantes",
    avatar: "EM",
    rating: 5,
    date: "2025-10-12",
    title: "HuntZen Jobs: UX Writing",
    content:
      "Finalmente uma plataforma que entende UX Writing! O HuntZen Jobs me sugeriu vagas que valorizam o content design. Obrigada HuntZen!",
    tags: ["UX Writing", "Conteudo"],
  },
  {
    id: 50,
    name: "Axel Thomas",
    role: "CTO de Startup",
    location: "Paris",
    avatar: "AT",
    rating: 5,
    date: "2025-10-10",
    title: "HuntZen Jobs: recrutamento tech simplificado",
    content:
      "Como CTO, uso o HuntZen Jobs para recrutar. Os perfis que passam pelo HuntZen sao de qualidade: CVs otimizados, candidatos preparados. O HuntZen eleva o nivel!",
    tags: ["CTO", "Recrutamento"],
  },
];
