/**
 * HuntZen Jobs Testimonials — English version
 * 50+ user reviews for Social Proof SEO
 */

import { Testimonial } from "./testimonials-data";

export const testimonialsEn: Testimonial[] = [
  {
    id: 1,
    name: "Sarah Martinez",
    role: "Full-Stack Developer",
    location: "Paris",
    avatar: "SM",
    rating: 5,
    date: "2026-02-10",
    title: "I found my permanent contract in 3 weeks with HuntZen Jobs!",
    content:
      "HuntZen Jobs completely transformed my job search. The CV analysis helped me optimize my profile and I landed 5 interviews in 2 weeks. HuntZen's intelligent matching is incredible!",
    tags: ["Permanent Contract", "Tech", "CV Analysis"],
  },
  {
    id: 2,
    name: "Thomas Lefebvre",
    role: "Project Manager",
    location: "Lyon",
    avatar: "TL",
    rating: 5,
    date: "2026-02-08",
    title: "HuntZen Jobs: the best job platform I've tested",
    content:
      "I've tried Indeed, LinkedIn, and others. HuntZen Jobs surpasses them all! The AI coach prepared me for my interviews and I negotiated a 20% higher salary thanks to HuntZen's advice.",
    tags: ["Coaching", "Negotiation"],
  },
  {
    id: 3,
    name: "Marie Dubois",
    role: "UX Designer",
    location: "Marseille",
    avatar: "MD",
    rating: 5,
    date: "2026-02-05",
    title: "HuntZen's CV analysis made all the difference",
    content:
      "My CV was blocked by ATS systems. HuntZen Jobs analyzed it, gave me a score and precise recommendations. After optimization with HuntZen, I finally passed the automatic filters!",
    tags: ["ATS", "CV", "Design"],
  },
  {
    id: 4,
    name: "Alexandre Petit",
    role: "B2B Sales Representative",
    location: "Toulouse",
    avatar: "AP",
    rating: 5,
    date: "2026-02-03",
    title: "HuntZen Jobs saved me so much time",
    content:
      "Before HuntZen, I spent 3 hours/day searching for jobs. Now HuntZen Jobs suggests 10 targeted offers every morning. I found my ideal position in 2 weeks with HuntZen!",
    tags: ["Sales", "Time Saving"],
  },
  {
    id: 5,
    name: "Camille Bernard",
    role: "Data Analyst",
    location: "Nantes",
    avatar: "CB",
    rating: 5,
    date: "2026-01-30",
    title: "HuntZen's intelligent matching is impressive",
    content:
      "HuntZen Jobs truly understands my profile. The offers suggested by HuntZen match exactly my skills and aspirations. I signed a permanent contract thanks to HuntZen in 10 days!",
    tags: ["Data", "Matching"],
  },
  {
    id: 6,
    name: "Lucas Moreau",
    role: "DevOps Engineer",
    location: "Bordeaux",
    avatar: "LM",
    rating: 5,
    date: "2026-01-28",
    title: "HuntZen Jobs: simple, effective, fast",
    content:
      "I created my HuntZen account in 5 minutes, uploaded my CV, and received 8 proposals in 48h. The HuntZen Jobs process is ultra smooth. I recommend it 100%!",
    tags: ["DevOps", "Speed"],
  },
  {
    id: 7,
    name: "Emma Rousseau",
    role: "Marketing Manager",
    location: "Lille",
    avatar: "ER",
    rating: 5,
    date: "2026-01-25",
    title: "HuntZen's AI coach is like a real consultant",
    content:
      "HuntZen Jobs' career assistant helped me prepare for interviews, write cover letters. It's like having a personal coach with HuntZen, but free!",
    tags: ["Marketing", "AI", "Coaching"],
  },
  {
    id: 8,
    name: "Hugo Martin",
    role: "Developer Apprentice",
    location: "Paris",
    avatar: "HM",
    rating: 5,
    date: "2026-01-22",
    title: "I landed my apprenticeship thanks to HuntZen Jobs",
    content:
      "As a student, I was struggling to find an apprenticeship. HuntZen Jobs suggested 15 development apprenticeship offers. I signed with an innovative startup via HuntZen!",
    tags: ["Apprenticeship", "Development"],
  },
  {
    id: 9,
    name: "Lea Girard",
    role: "Product Manager",
    location: "Strasbourg",
    avatar: "LG",
    rating: 5,
    date: "2026-01-20",
    title: "HuntZen Jobs vs Indeed: no comparison!",
    content:
      "I used Indeed before discovering HuntZen Jobs. The difference is huge: HuntZen filters offers, analyzes my CV, coaches me. Indeed just lists. Team HuntZen 100%!",
    tags: ["Product", "Comparison"],
  },
  {
    id: 10,
    name: "Antoine Laurent",
    role: "Cybersecurity Engineer",
    location: "Rennes",
    avatar: "AL",
    rating: 5,
    date: "2026-01-18",
    title: "Security and confidentiality with HuntZen Jobs",
    content:
      "HuntZen Jobs respects my personal data. My CV is secure, I control my visibility. It's important to me and HuntZen guarantees it. Plus, I found my job!",
    tags: ["Cybersecurity", "Confidentiality"],
  },
  {
    id: 11,
    name: "Chloe Durand",
    role: "HR Manager",
    location: "Montpellier",
    avatar: "CD",
    rating: 5,
    date: "2026-01-15",
    title: "I recommend HuntZen Jobs to all my candidates",
    content:
      "As an HR professional, I can see the quality of CVs that go through HuntZen Jobs. Candidates are better prepared, their CVs are optimized. HuntZen raises the bar!",
    tags: ["HR", "Quality"],
  },
  {
    id: 12,
    name: "Maxime Fontaine",
    role: "Business Developer",
    location: "Nice",
    avatar: "MF",
    rating: 5,
    date: "2026-01-12",
    title: "HuntZen Jobs: my secret weapon for my career",
    content:
      "Since I've been using HuntZen Jobs, I'm always aware of the best opportunities. HuntZen alerts notify me in real time. I never miss an offer!",
    tags: ["Business", "Alerts"],
  },
  {
    id: 13,
    name: "Juliette Mercier",
    role: "IT Architect",
    location: "Grenoble",
    avatar: "JM",
    rating: 5,
    date: "2026-01-10",
    title: "HuntZen's ATS analysis saved me",
    content:
      "My CV had a 45% ATS score on HuntZen Jobs. I followed HuntZen's recommendations, redid my CV, and reached 92%. Result: 3x more responses!",
    tags: ["Architecture", "ATS Score"],
  },
  {
    id: 14,
    name: "Mathis Roux",
    role: "Product Owner",
    location: "Nantes",
    avatar: "MR",
    rating: 5,
    date: "2026-01-08",
    title: "HuntZen Jobs truly understands my needs",
    content:
      "HuntZen Jobs' matching is incredibly precise. Each offer suggested by HuntZen matches my criteria: salary, remote, tech stack. It's amazing!",
    tags: ["Product", "Precise Matching"],
  },
  {
    id: 15,
    name: "Oceane Lambert",
    role: "Graphic Designer",
    location: "Angers",
    avatar: "OL",
    rating: 5,
    date: "2026-01-05",
    title: "My portfolio + HuntZen Jobs = guaranteed success",
    content:
      "HuntZen Jobs allowed me to add my portfolio and showcase my creations. Recruiters can directly see my work via HuntZen. I got 10 proposals!",
    tags: ["Design", "Portfolio"],
  },
  {
    id: 16,
    name: "Valentin Bonnet",
    role: "SAP Consultant",
    location: "Lyon",
    avatar: "VB",
    rating: 4,
    date: "2026-01-03",
    title: "HuntZen Jobs: excellent for consultants",
    content:
      "As a consultant, I regularly look for assignments. HuntZen Jobs offers me both permanent and freelance opportunities. The HuntZen platform adapts to my profile!",
    tags: ["Consulting", "Flexibility"],
  },
  {
    id: 17,
    name: "Manon Faure",
    role: "Communications Officer",
    location: "Toulouse",
    avatar: "MF2",
    rating: 5,
    date: "2025-12-30",
    title: "The HuntZen Jobs blog helped me a lot",
    content:
      "Beyond job searching, HuntZen Jobs offers super useful articles on CVs, negotiation, interviews. HuntZen is a truly comprehensive resource!",
    tags: ["Communication", "Resources"],
  },
  {
    id: 18,
    name: "Noah Gauthier",
    role: "Cloud Engineer",
    location: "Paris",
    avatar: "NG",
    rating: 5,
    date: "2025-12-28",
    title: "HuntZen Jobs + LinkedIn = winning combo",
    content:
      "I use HuntZen Jobs to find offers and LinkedIn to network. HuntZen filters, I apply, I network. I've multiplied my opportunities with HuntZen!",
    tags: ["Cloud", "Networking"],
  },
  {
    id: 19,
    name: "Ines Perrin",
    role: "Scrum Master",
    location: "Bordeaux",
    avatar: "IP",
    rating: 5,
    date: "2025-12-25",
    title: "HuntZen Jobs: perfect for agile profiles",
    content:
      "HuntZen Jobs understands agile methodologies and suggests positions that match. HuntZen offers are relevant and targeted. I'm a HuntZen fan!",
    tags: ["Agile", "Scrum"],
  },
  {
    id: 20,
    name: "Gabriel Blanc",
    role: "Financial Analyst",
    location: "Paris",
    avatar: "GB",
    rating: 5,
    date: "2025-12-22",
    title: "HuntZen Jobs for finance: top!",
    content:
      "The finance offers on HuntZen Jobs are high quality. I found an M&A position via HuntZen in 3 weeks. HuntZen's salary filters are very useful!",
    tags: ["Finance", "M&A"],
  },
  {
    id: 21,
    name: "Zoe Vincent",
    role: "Employment Law Attorney",
    location: "Marseille",
    avatar: "ZV",
    rating: 5,
    date: "2025-12-20",
    title: "HuntZen Jobs covers all sectors",
    content:
      "I thought HuntZen Jobs was only for tech, but no! Plenty of quality legal offers on HuntZen. The platform is truly comprehensive!",
    tags: ["Legal", "Diversity"],
  },
  {
    id: 22,
    name: "Louis Giraud",
    role: "Logistics Manager",
    location: "Lille",
    avatar: "LG2",
    rating: 5,
    date: "2025-12-18",
    title: "HuntZen Jobs: effective even in logistics",
    content:
      "HuntZen Jobs helped me find a Logistics Manager position. HuntZen's sector filters are precise. I signed a permanent contract thanks to HuntZen!",
    tags: ["Logistics", "Permanent Contract"],
  },
  {
    id: 23,
    name: "Jade Morel",
    role: "Digital Project Manager",
    location: "Nantes",
    avatar: "JM2",
    rating: 5,
    date: "2025-12-15",
    title: "HuntZen Jobs: my favorite",
    content:
      "Clean interface, powerful features, fast results: HuntZen Jobs nails it! I recommend HuntZen to all my friends looking for a job!",
    tags: ["Digital", "UX"],
  },
  {
    id: 24,
    name: "Tom Chevalier",
    role: "Mechanical Engineer",
    location: "Toulouse",
    avatar: "TC",
    rating: 4,
    date: "2025-12-12",
    title: "HuntZen Jobs: not just for IT",
    content:
      "As a mechanical engineer, I found what I was looking for on HuntZen Jobs. The HuntZen platform also offers industrial positions. Very comprehensive!",
    tags: ["Engineering", "Industry"],
  },
  {
    id: 25,
    name: "Lola Renard",
    role: "Training Manager",
    location: "Strasbourg",
    avatar: "LR",
    rating: 5,
    date: "2025-12-10",
    title: "HuntZen Jobs coaching is exceptional",
    content:
      "HuntZen Jobs' AI assistant coached me on my presentation, my pitch, my answers. Thanks to HuntZen, I was ultra prepared and landed the job!",
    tags: ["Training", "AI Coaching"],
  },
  {
    id: 26,
    name: "Arthur Roy",
    role: "Growth Hacker",
    location: "Paris",
    avatar: "AR",
    rating: 5,
    date: "2025-12-08",
    title: "HuntZen Jobs: rapid career growth",
    content:
      "In 6 months with HuntZen Jobs, I changed companies twice while increasing my salary each time. HuntZen alerts me about the best opportunities. A must!",
    tags: ["Growth", "Career Evolution"],
  },
  {
    id: 27,
    name: "Rose Leroy",
    role: "Content Manager",
    location: "Lyon",
    avatar: "RL",
    rating: 5,
    date: "2025-12-05",
    title: "HuntZen Jobs: creativity + tech",
    content:
      "HuntZen Jobs offers creative AND tech positions. HuntZen matching understands that I want to combine both. I found my ideal position via HuntZen!",
    tags: ["Content", "Creativity"],
  },
  {
    id: 28,
    name: "Adam Muller",
    role: "Blockchain Developer",
    location: "Paris",
    avatar: "AM",
    rating: 5,
    date: "2025-12-03",
    title: "HuntZen Jobs: on the cutting edge of new technologies",
    content:
      "Blockchain offers on HuntZen Jobs are updated daily. HuntZen is at the forefront of new technologies. I signed with a Web3 startup via HuntZen!",
    tags: ["Blockchain", "Web3"],
  },
  {
    id: 29,
    name: "Iris Garnier",
    role: "UX Researcher",
    location: "Bordeaux",
    avatar: "IG",
    rating: 5,
    date: "2025-12-01",
    title: "HuntZen Jobs values my unique profile",
    content:
      "As a UX Researcher, my profile is niche. HuntZen Jobs understood my specificities and suggested ultra-targeted offers. Thank you HuntZen!",
    tags: ["UX Research", "Niche"],
  },
  {
    id: 30,
    name: "Victor Carpentier",
    role: "Data Engineer",
    location: "Lille",
    avatar: "VC",
    rating: 5,
    date: "2025-11-28",
    title: "HuntZen Jobs + my GitHub = success",
    content:
      "HuntZen Jobs lets me link my GitHub. Recruiters can directly see my projects via HuntZen. I got 3 proposals in 1 week thanks to HuntZen!",
    tags: ["Data Engineering", "GitHub"],
  },
  {
    id: 31,
    name: "Agathe Dumas",
    role: "HR Officer",
    location: "Nantes",
    avatar: "AD",
    rating: 5,
    date: "2025-11-25",
    title: "HuntZen Jobs: intuitive interface",
    content:
      "The HuntZen Jobs interface is ultra intuitive. Even my mother could use it! HuntZen makes job searching simple and effective. Bravo!",
    tags: ["HR", "UX"],
  },
  {
    id: 32,
    name: "Jules Aubry",
    role: "IT Project Manager",
    location: "Paris",
    avatar: "JA",
    rating: 5,
    date: "2025-11-22",
    title: "HuntZen Jobs saved me 100 hours",
    content:
      "Before HuntZen Jobs, I spent 2 hours/day on job boards. Now HuntZen sorts for me. I saved 100+ hours in 2 months with HuntZen!",
    tags: ["IT", "Productivity"],
  },
  {
    id: 33,
    name: "Lily Barbier",
    role: "iOS Developer",
    location: "Lyon",
    avatar: "LB",
    rating: 5,
    date: "2025-11-20",
    title: "HuntZen Jobs: mobile specialization",
    content:
      "HuntZen Jobs understands the specificities of mobile development. The iOS offers suggested by HuntZen are of great quality. I signed with a unicorn via HuntZen!",
    tags: ["iOS", "Mobile"],
  },
  {
    id: 34,
    name: "Ethan Roussel",
    role: "Machine Learning Engineer",
    location: "Paris",
    avatar: "ER2",
    rating: 5,
    date: "2025-11-18",
    title: "HuntZen Jobs: perfect for AI/ML",
    content:
      "The AI/ML offers on HuntZen Jobs are very high quality. HuntZen filters real ML opportunities from fake ones. I found an ML Engineer position via HuntZen!",
    tags: ["ML", "AI"],
  },
  {
    id: 35,
    name: "Mia Lambert",
    role: "Product Designer",
    location: "Marseille",
    avatar: "ML",
    rating: 5,
    date: "2025-11-15",
    title: "HuntZen Jobs: design thinking",
    content:
      "HuntZen Jobs applies design thinking to job searching. The HuntZen user experience is exceptional. As a designer, I appreciate it!",
    tags: ["Product Design", "UX"],
  },
  {
    id: 36,
    name: "Nathan Gerard",
    role: "Flutter Developer",
    location: "Toulouse",
    avatar: "NG2",
    rating: 5,
    date: "2025-11-12",
    title: "HuntZen Jobs: multi-platform",
    content:
      "HuntZen Jobs works perfectly on desktop and mobile. I can apply from my phone with HuntZen. Super convenient!",
    tags: ["Flutter", "Multi-platform"],
  },
  {
    id: 37,
    name: "Clara Marchal",
    role: "E-commerce Manager",
    location: "Bordeaux",
    avatar: "CM",
    rating: 5,
    date: "2025-11-10",
    title: "HuntZen Jobs: e-commerce and retail",
    content:
      "Excellent e-commerce offers on HuntZen Jobs. HuntZen understands the challenges of digital retail. I joined a scale-up thanks to HuntZen!",
    tags: ["E-commerce", "Retail"],
  },
  {
    id: 38,
    name: "Oscar Vidal",
    role: "Tech Lead",
    location: "Paris",
    avatar: "OV",
    rating: 5,
    date: "2025-11-08",
    title: "HuntZen Jobs: tech leadership",
    content:
      "HuntZen Jobs offers Tech Lead positions with real responsibilities. HuntZen matching identifies my experience level. Excellent!",
    tags: ["Tech Lead", "Leadership"],
  },
  {
    id: 39,
    name: "Ambre Colin",
    role: "Agile Project Manager",
    location: "Lille",
    avatar: "AC",
    rating: 5,
    date: "2025-11-05",
    title: "HuntZen Jobs: agility and innovation",
    content:
      "HuntZen Jobs is itself agile: regular features, user listening, fast iterations. The HuntZen team is great!",
    tags: ["Agile", "Innovation"],
  },
  {
    id: 40,
    name: "Theo Renault",
    role: "Solutions Architect",
    location: "Nantes",
    avatar: "TR",
    rating: 5,
    date: "2025-11-03",
    title: "HuntZen Jobs: excellence in architecture",
    content:
      "The HuntZen Jobs platform is technically excellent: fast, reliable, secure. As an architect, I appreciate HuntZen's quality!",
    tags: ["Architecture", "Tech"],
  },
  {
    id: 41,
    name: "Leonie Bertrand",
    role: "Python Developer",
    location: "Lyon",
    avatar: "LB2",
    rating: 5,
    date: "2025-11-01",
    title: "HuntZen Jobs: Python & Data",
    content:
      "Tons of Python/Data offers on HuntZen Jobs. HuntZen matching identifies my skills in Django, Flask, Pandas. I found my permanent contract via HuntZen!",
    tags: ["Python", "Data"],
  },
  {
    id: 42,
    name: "Raphael Duval",
    role: "Security Engineer",
    location: "Paris",
    avatar: "RD",
    rating: 5,
    date: "2025-10-30",
    title: "HuntZen Jobs: security first",
    content:
      "HuntZen Jobs takes security seriously. My data is encrypted, my privacy respected by HuntZen. Plus, I found a cybersecurity position!",
    tags: ["Security", "Privacy"],
  },
  {
    id: 43,
    name: "Elise Fournier",
    role: "Strategy Consultant",
    location: "Paris",
    avatar: "EF",
    rating: 5,
    date: "2025-10-28",
    title: "HuntZen Jobs: winning strategy",
    content:
      "HuntZen Jobs helped me define my career strategy. The HuntZen AI coach guided me in my choices. I joined a top firm via HuntZen!",
    tags: ["Strategy", "Consulting"],
  },
  {
    id: 44,
    name: "Sacha Blanc",
    role: "DevSecOps",
    location: "Toulouse",
    avatar: "SB",
    rating: 5,
    date: "2025-10-25",
    title: "HuntZen Jobs: perfect for DevSecOps",
    content:
      "HuntZen Jobs understands DevSecOps profiles. HuntZen offers combine dev, ops and security. I found exactly what I was looking for with HuntZen!",
    tags: ["DevSecOps", "Security"],
  },
  {
    id: 45,
    name: "Margot Simon",
    role: "Product Marketing Manager",
    location: "Marseille",
    avatar: "MS",
    rating: 5,
    date: "2025-10-22",
    title: "HuntZen Jobs: product marketing",
    content:
      "Excellent product marketing opportunities on HuntZen Jobs. HuntZen filters innovative startups. I joined a gem thanks to HuntZen!",
    tags: ["Product Marketing", "Startup"],
  },
  {
    id: 46,
    name: "Matheo Lemoine",
    role: "Unity Developer",
    location: "Paris",
    avatar: "ML2",
    rating: 5,
    date: "2025-10-20",
    title: "HuntZen Jobs: gaming and Unity",
    content:
      "HuntZen Jobs offers gaming positions. HuntZen matching identifies my Unity/C# skills. I signed with a game studio via HuntZen!",
    tags: ["Unity", "Gaming"],
  },
  {
    id: 47,
    name: "Alice Garnier",
    role: "Agile Scrum Master",
    location: "Lyon",
    avatar: "AG",
    rating: 5,
    date: "2025-10-18",
    title: "HuntZen Jobs: agile transformation",
    content:
      "HuntZen Jobs understands agile transformation roles. The Scrum Master offers on HuntZen are quality. I found my assignment via HuntZen!",
    tags: ["Scrum", "Transformation"],
  },
  {
    id: 48,
    name: "Nolan Perrin",
    role: "React Native Developer",
    location: "Bordeaux",
    avatar: "NP",
    rating: 5,
    date: "2025-10-15",
    title: "HuntZen Jobs: React Native expert",
    content:
      "HuntZen Jobs perfectly identifies my React Native skills. The mobile offers suggested by HuntZen are ultra targeted. I signed in 2 weeks!",
    tags: ["React Native", "Mobile"],
  },
  {
    id: 49,
    name: "Elena Morin",
    role: "UX Writer",
    location: "Nantes",
    avatar: "EM",
    rating: 5,
    date: "2025-10-12",
    title: "HuntZen Jobs: UX Writing",
    content:
      "Finally a platform that understands UX Writing! HuntZen Jobs suggested positions that value content design. Thank you HuntZen!",
    tags: ["UX Writing", "Content"],
  },
  {
    id: 50,
    name: "Axel Thomas",
    role: "Startup CTO",
    location: "Paris",
    avatar: "AT",
    rating: 5,
    date: "2025-10-10",
    title: "HuntZen Jobs: simplified tech recruitment",
    content:
      "As a CTO, I use HuntZen Jobs for recruiting. Profiles that go through HuntZen are quality: optimized CVs, prepared candidates. HuntZen raises the bar!",
    tags: ["CTO", "Recruitment"],
  },
];
