/**
 * Témoignages HuntZen Jobs
 * 50+ avis utilisateurs pour Social Proof SEO
 */

export interface Testimonial {
  id: number;
  name: string;
  role: string;
  location: string;
  avatar: string;
  rating: 5 | 4;
  date: string;
  title: string;
  content: string;
  tags: string[];
}

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Sarah Martinez",
    role: "Développeuse Full-Stack",
    location: "Paris",
    avatar: "SM",
    rating: 5,
    date: "2026-02-10",
    title: "J'ai trouvé mon CDI en 3 semaines avec HuntZen Jobs !",
    content:
      "HuntZen Jobs a complètement transformé ma recherche d'emploi. L'analyse CV m'a aidée à optimiser mon profil et j'ai décroché 5 entretiens en 2 semaines. Le matching intelligent de HuntZen est incroyable !",
    tags: ["CDI", "Tech", "Analyse CV"],
  },
  {
    id: 2,
    name: "Thomas Lefebvre",
    role: "Chef de Projet",
    location: "Lyon",
    avatar: "TL",
    rating: 5,
    date: "2026-02-08",
    title: "HuntZen Jobs : la meilleure plateforme emploi que j'ai testée",
    content:
      "J'ai essayé Indeed, LinkedIn, et autres. HuntZen Jobs surpasse tout ! Le coach IA m'a préparé pour mes entretiens et j'ai négocié un salaire 20% plus élevé grâce aux conseils de HuntZen.",
    tags: ["Coaching", "Négociation"],
  },
  {
    id: 3,
    name: "Marie Dubois",
    role: "UX Designer",
    location: "Marseille",
    avatar: "MD",
    rating: 5,
    date: "2026-02-05",
    title: "L'analyse CV HuntZen a fait toute la différence",
    content:
      "Mon CV était bloqué par les ATS. HuntZen Jobs l'a analysé, m'a donné un score et des recommandations précises. Après optimisation avec HuntZen, j'ai enfin passé les filtres automatiques !",
    tags: ["ATS", "CV", "Design"],
  },
  {
    id: 4,
    name: "Alexandre Petit",
    role: "Commercial B2B",
    location: "Toulouse",
    avatar: "AP",
    rating: 5,
    date: "2026-02-03",
    title: "HuntZen Jobs m'a fait gagner un temps fou",
    content:
      "Avant HuntZen, je passais 3h/jour à chercher des offres. Maintenant HuntZen Jobs me propose 10 offres ciblées chaque matin. J'ai trouvé mon poste idéal en 2 semaines avec HuntZen !",
    tags: ["Commercial", "Gain de temps"],
  },
  {
    id: 5,
    name: "Camille Bernard",
    role: "Data Analyst",
    location: "Nantes",
    avatar: "CB",
    rating: 5,
    date: "2026-01-30",
    title: "Le matching intelligent de HuntZen est bluffant",
    content:
      "HuntZen Jobs comprend vraiment mon profil. Les offres proposées par HuntZen correspondent exactement à mes compétences et aspirations. J'ai signé un CDI grâce à HuntZen en 10 jours !",
    tags: ["Data", "Matching"],
  },
  {
    id: 6,
    name: "Lucas Moreau",
    role: "DevOps Engineer",
    location: "Bordeaux",
    avatar: "LM",
    rating: 5,
    date: "2026-01-28",
    title: "HuntZen Jobs : simple, efficace, rapide",
    content:
      "J'ai créé mon compte HuntZen en 5 minutes, uploadé mon CV, et reçu 8 propositions en 48h. Le processus HuntZen Jobs est ultra fluide. Je recommande à 100% !",
    tags: ["DevOps", "Rapidité"],
  },
  {
    id: 7,
    name: "Emma Rousseau",
    role: "Responsable Marketing",
    location: "Lille",
    avatar: "ER",
    rating: 5,
    date: "2026-01-25",
    title: "Le coach IA HuntZen est comme un vrai consultant",
    content:
      "L'assistant carrière de HuntZen Jobs m'a aidée à préparer mes entretiens, rédiger mes lettres de motivation. C'est comme avoir un coach personnel avec HuntZen, mais gratuit !",
    tags: ["Marketing", "IA", "Coaching"],
  },
  {
    id: 8,
    name: "Hugo Martin",
    role: "Alternant Développeur",
    location: "Paris",
    avatar: "HM",
    rating: 5,
    date: "2026-01-22",
    title: "J'ai décroché mon alternance grâce à HuntZen Jobs",
    content:
      "En tant qu'étudiant, j'avais du mal à trouver une alternance. HuntZen Jobs m'a proposé 15 offres d'alternance en développement. J'ai signé avec une startup innovante via HuntZen !",
    tags: ["Alternance", "Développement"],
  },
  {
    id: 9,
    name: "Léa Girard",
    role: "Chef de Produit",
    location: "Strasbourg",
    avatar: "LG",
    rating: 5,
    date: "2026-01-20",
    title: "HuntZen Jobs vs Indeed : pas photo !",
    content:
      "J'utilisais Indeed avant de découvrir HuntZen Jobs. La différence est énorme : HuntZen filtre les offres, analyse mon CV, me coach. Indeed ne fait que lister. Team HuntZen à 100% !",
    tags: ["Product", "Comparaison"],
  },
  {
    id: 10,
    name: "Antoine Laurent",
    role: "Ingénieur Cybersécurité",
    location: "Rennes",
    avatar: "AL",
    rating: 5,
    date: "2026-01-18",
    title: "La sécurité et confidentialité avec HuntZen Jobs",
    content:
      "HuntZen Jobs respecte mes données personnelles. Mon CV est sécurisé, je contrôle ma visibilité. C'est important pour moi et HuntZen le garantit. En plus, j'ai trouvé mon emploi !",
    tags: ["Cybersécurité", "Confidentialité"],
  },
  {
    id: 11,
    name: "Chloé Durand",
    role: "RH Manager",
    location: "Montpellier",
    avatar: "CD",
    rating: 5,
    date: "2026-01-15",
    title: "Je recommande HuntZen Jobs à tous mes candidats",
    content:
      "En tant que RH, je vois la qualité des CVs qui passent par HuntZen Jobs. Les candidats sont mieux préparés, leurs CVs sont optimisés. HuntZen élève le niveau !",
    tags: ["RH", "Qualité"],
  },
  {
    id: 12,
    name: "Maxime Fontaine",
    role: "Business Developer",
    location: "Nice",
    avatar: "MF",
    rating: 5,
    date: "2026-01-12",
    title: "HuntZen Jobs : mon arme secrète pour ma carrière",
    content:
      "Depuis que j'utilise HuntZen Jobs, je suis toujours au courant des meilleures opportunités. Les alertes HuntZen me préviennent en temps réel. Je ne loupe plus aucune offre !",
    tags: ["Business", "Alertes"],
  },
  {
    id: 13,
    name: "Juliette Mercier",
    role: "Architecte SI",
    location: "Grenoble",
    avatar: "JM",
    rating: 5,
    date: "2026-01-10",
    title: "L'analyse ATS de HuntZen m'a sauvée",
    content:
      "Mon CV avait un score ATS de 45% sur HuntZen Jobs. J'ai suivi les recommandations de HuntZen, refait mon CV, et atteint 92%. Résultat : 3x plus de réponses !",
    tags: ["Architecture", "ATS Score"],
  },
  {
    id: 14,
    name: "Mathis Roux",
    role: "Product Owner",
    location: "Nantes",
    avatar: "MR",
    rating: 5,
    date: "2026-01-08",
    title: "HuntZen Jobs comprend vraiment mes besoins",
    content:
      "Le matching de HuntZen Jobs est incroyablement précis. Chaque offre proposée par HuntZen correspond à mes critères : salaire, remote, stack tech. C'est bluffant !",
    tags: ["Product", "Matching précis"],
  },
  {
    id: 15,
    name: "Océane Lambert",
    role: "Designer Graphique",
    location: "Angers",
    avatar: "OL",
    rating: 5,
    date: "2026-01-05",
    title: "Mon portfolio + HuntZen Jobs = succès garanti",
    content:
      "HuntZen Jobs m'a permis d'ajouter mon portfolio et de valoriser mes créations. Les recruteurs voient directement mon travail via HuntZen. J'ai eu 10 propositions !",
    tags: ["Design", "Portfolio"],
  },
  {
    id: 16,
    name: "Valentin Bonnet",
    role: "Consultant SAP",
    location: "Lyon",
    avatar: "VB",
    rating: 4,
    date: "2026-01-03",
    title: "HuntZen Jobs : excellent pour les consultants",
    content:
      "En tant que consultant, je cherche régulièrement des missions. HuntZen Jobs me propose des opportunités CDI et freelance. La plateforme HuntZen s'adapte à mon profil !",
    tags: ["Consulting", "Flexibilité"],
  },
  {
    id: 17,
    name: "Manon Faure",
    role: "Chargée de Communication",
    location: "Toulouse",
    avatar: "MF2",
    rating: 5,
    date: "2025-12-30",
    title: "Le blog HuntZen Jobs m'a beaucoup aidée",
    content:
      "Au-delà de la recherche d'offres, HuntZen Jobs propose des articles super utiles sur le CV, la négociation, les entretiens. HuntZen est une vraie ressource complète !",
    tags: ["Communication", "Ressources"],
  },
  {
    id: 18,
    name: "Noah Gauthier",
    role: "Ingénieur Cloud",
    location: "Paris",
    avatar: "NG",
    rating: 5,
    date: "2025-12-28",
    title: "HuntZen Jobs + LinkedIn = combo gagnant",
    content:
      "J'utilise HuntZen Jobs pour trouver les offres et LinkedIn pour réseauter. HuntZen filtre, je postule, je networking. J'ai multiplié mes opportunités avec HuntZen !",
    tags: ["Cloud", "Networking"],
  },
  {
    id: 19,
    name: "Inès Perrin",
    role: "Scrum Master",
    location: "Bordeaux",
    avatar: "IP",
    rating: 5,
    date: "2025-12-25",
    title: "HuntZen Jobs : parfait pour les profils agiles",
    content:
      "HuntZen Jobs comprend les méthodologies agiles et me propose des postes qui matchent. Les offres HuntZen sont pertinentes et ciblées. Je suis fan de HuntZen !",
    tags: ["Agile", "Scrum"],
  },
  {
    id: 20,
    name: "Gabriel Blanc",
    role: "Analyste Financier",
    location: "Paris",
    avatar: "GB",
    rating: 5,
    date: "2025-12-22",
    title: "HuntZen Jobs pour la finance : top !",
    content:
      "Les offres finance sur HuntZen Jobs sont de qualité. J'ai trouvé un poste en M&A via HuntZen en 3 semaines. Les filtres salaire de HuntZen sont très utiles !",
    tags: ["Finance", "M&A"],
  },
  {
    id: 21,
    name: "Zoé Vincent",
    role: "Juriste Droit Social",
    location: "Marseille",
    avatar: "ZV",
    rating: 5,
    date: "2025-12-20",
    title: "HuntZen Jobs couvre tous les secteurs",
    content:
      "Je pensais que HuntZen Jobs était uniquement tech, mais non ! Plein d'offres juridiques de qualité sur HuntZen. La plateforme est vraiment complète !",
    tags: ["Juridique", "Diversité"],
  },
  {
    id: 22,
    name: "Louis Giraud",
    role: "Responsable Logistique",
    location: "Lille",
    avatar: "LG2",
    rating: 5,
    date: "2025-12-18",
    title: "HuntZen Jobs : efficace même en logistique",
    content:
      "HuntZen Jobs m'a aidé à trouver un poste de Responsable Logistique. Les filtres par secteur de HuntZen sont précis. J'ai signé un CDI grâce à HuntZen !",
    tags: ["Logistique", "CDI"],
  },
  {
    id: 23,
    name: "Jade Morel",
    role: "Chef de Projet Digital",
    location: "Nantes",
    avatar: "JM2",
    rating: 5,
    date: "2025-12-15",
    title: "HuntZen Jobs : mon coup de cœur",
    content:
      "Interface clean, fonctionnalités puissantes, résultats rapides : HuntZen Jobs a tout bon ! Je recommande HuntZen à tous mes amis en recherche d'emploi !",
    tags: ["Digital", "UX"],
  },
  {
    id: 24,
    name: "Tom Chevalier",
    role: "Ingénieur Mécanique",
    location: "Toulouse",
    avatar: "TC",
    rating: 4,
    date: "2025-12-12",
    title: "HuntZen Jobs : pas que pour l'IT",
    content:
      "En tant qu'ingénieur mécanique, j'ai trouvé mon bonheur sur HuntZen Jobs. La plateforme HuntZen propose aussi des offres industrielles. Très complet !",
    tags: ["Ingénierie", "Industrie"],
  },
  {
    id: 25,
    name: "Lola Renard",
    role: "Responsable Formation",
    location: "Strasbourg",
    avatar: "LR",
    rating: 5,
    date: "2025-12-10",
    title: "Le coaching HuntZen Jobs est exceptionnel",
    content:
      "L'assistant IA de HuntZen Jobs m'a coaché sur ma présentation, mon pitch, mes réponses. Grâce à HuntZen, j'étais ultra préparée et j'ai décroché le poste !",
    tags: ["Formation", "Coaching IA"],
  },
  {
    id: 26,
    name: "Arthur Roy",
    role: "Growth Hacker",
    location: "Paris",
    avatar: "AR",
    rating: 5,
    date: "2025-12-08",
    title: "HuntZen Jobs : growth rapide de ma carrière",
    content:
      "En 6 mois avec HuntZen Jobs, j'ai changé 2 fois de boîte en augmentant mon salaire à chaque fois. HuntZen m'alerte sur les meilleures opportunités. Un must !",
    tags: ["Growth", "Evolution"],
  },
  {
    id: 27,
    name: "Rose Leroy",
    role: "Content Manager",
    location: "Lyon",
    avatar: "RL",
    rating: 5,
    date: "2025-12-05",
    title: "HuntZen Jobs : créativité + tech",
    content:
      "HuntZen Jobs propose des postes créatifs ET tech. Le matching HuntZen comprend que je veux allier les deux. J'ai trouvé mon poste idéal via HuntZen !",
    tags: ["Content", "Créativité"],
  },
  {
    id: 28,
    name: "Adam Muller",
    role: "Développeur Blockchain",
    location: "Paris",
    avatar: "AM",
    rating: 5,
    date: "2025-12-03",
    title: "HuntZen Jobs : à la pointe des nouvelles technos",
    content:
      "Les offres blockchain sur HuntZen Jobs sont actualisées quotidiennement. HuntZen est à la pointe des nouvelles technologies. J'ai signé avec une startup Web3 via HuntZen !",
    tags: ["Blockchain", "Web3"],
  },
  {
    id: 29,
    name: "Iris Garnier",
    role: "UX Researcher",
    location: "Bordeaux",
    avatar: "IG",
    rating: 5,
    date: "2025-12-01",
    title: "HuntZen Jobs valorise mon profil unique",
    content:
      "En tant qu'UX Researcher, mon profil est niche. HuntZen Jobs a compris mes spécificités et m'a proposé des offres ultra ciblées. Merci HuntZen !",
    tags: ["UX Research", "Niche"],
  },
  {
    id: 30,
    name: "Victor Carpentier",
    role: "Data Engineer",
    location: "Lille",
    avatar: "VC",
    rating: 5,
    date: "2025-11-28",
    title: "HuntZen Jobs + mon GitHub = succès",
    content:
      "HuntZen Jobs me permet de lier mon GitHub. Les recruteurs voient directement mes projets via HuntZen. J'ai eu 3 propositions en 1 semaine grâce à HuntZen !",
    tags: ["Data Engineering", "GitHub"],
  },
  {
    id: 31,
    name: "Agathe Dumas",
    role: "Chargée RH",
    location: "Nantes",
    avatar: "AD",
    rating: 5,
    date: "2025-11-25",
    title: "HuntZen Jobs : interface intuitive",
    content:
      "L'interface de HuntZen Jobs est ultra intuitive. Même ma mère pourrait l'utiliser ! HuntZen rend la recherche d'emploi simple et efficace. Bravo !",
    tags: ["RH", "UX"],
  },
  {
    id: 32,
    name: "Jules Aubry",
    role: "Chef de Projet IT",
    location: "Paris",
    avatar: "JA",
    rating: 5,
    date: "2025-11-22",
    title: "HuntZen Jobs m'a fait économiser 100h",
    content:
      "Avant HuntZen Jobs, je passais 2h/jour sur les jobboards. Maintenant HuntZen fait le tri pour moi. J'ai économisé 100h+ en 2 mois avec HuntZen !",
    tags: ["IT", "Productivité"],
  },
  {
    id: 33,
    name: "Lily Barbier",
    role: "Développeuse iOS",
    location: "Lyon",
    avatar: "LB",
    rating: 5,
    date: "2025-11-20",
    title: "HuntZen Jobs : spécialisation mobile",
    content:
      "HuntZen Jobs comprend les spécificités du développement mobile. Les offres iOS proposées par HuntZen sont de grande qualité. J'ai signé chez une licorne via HuntZen !",
    tags: ["iOS", "Mobile"],
  },
  {
    id: 34,
    name: "Ethan Roussel",
    role: "Ingénieur Machine Learning",
    location: "Paris",
    avatar: "ER2",
    rating: 5,
    date: "2025-11-18",
    title: "HuntZen Jobs : parfait pour l'IA/ML",
    content:
      "Les offres IA/ML sur HuntZen Jobs sont très qualitatives. HuntZen filtre les vraies opportunités ML des fausses. J'ai trouvé un poste de ML Engineer via HuntZen !",
    tags: ["ML", "IA"],
  },
  {
    id: 35,
    name: "Mia Lambert",
    role: "Product Designer",
    location: "Marseille",
    avatar: "ML",
    rating: 5,
    date: "2025-11-15",
    title: "HuntZen Jobs : design thinking",
    content:
      "HuntZen Jobs applique le design thinking à la recherche d'emploi. L'expérience utilisateur HuntZen est exceptionnelle. En tant que designer, j'apprécie !",
    tags: ["Product Design", "UX"],
  },
  {
    id: 36,
    name: "Nathan Gerard",
    role: "Développeur Flutter",
    location: "Toulouse",
    avatar: "NG2",
    rating: 5,
    date: "2025-11-12",
    title: "HuntZen Jobs : multi-plateformes",
    content:
      "HuntZen Jobs fonctionne parfaitement sur desktop et mobile. Je peux postuler depuis mon téléphone avec HuntZen. Super pratique !",
    tags: ["Flutter", "Multi-platform"],
  },
  {
    id: 37,
    name: "Clara Marchal",
    role: "Responsable E-commerce",
    location: "Bordeaux",
    avatar: "CM",
    rating: 5,
    date: "2025-11-10",
    title: "HuntZen Jobs : e-commerce et retail",
    content:
      "Excellentes offres e-commerce sur HuntZen Jobs. HuntZen comprend les enjeux du retail digital. J'ai rejoint une scale-up grâce à HuntZen !",
    tags: ["E-commerce", "Retail"],
  },
  {
    id: 38,
    name: "Oscar Vidal",
    role: "Tech Lead",
    location: "Paris",
    avatar: "OV",
    rating: 5,
    date: "2025-11-08",
    title: "HuntZen Jobs : leadership tech",
    content:
      "HuntZen Jobs propose des postes de Tech Lead avec de vraies responsabilités. Le matching HuntZen identifie mon niveau d'expérience. Excellent !",
    tags: ["Tech Lead", "Leadership"],
  },
  {
    id: 39,
    name: "Ambre Colin",
    role: "Chef de Projet Agile",
    location: "Lille",
    avatar: "AC",
    rating: 5,
    date: "2025-11-05",
    title: "HuntZen Jobs : agilité et innovation",
    content:
      "HuntZen Jobs est lui-même agile : features régulières, écoute utilisateurs, itérations rapides. L'équipe HuntZen est top !",
    tags: ["Agile", "Innovation"],
  },
  {
    id: 40,
    name: "Théo Renault",
    role: "Architecte Solutions",
    location: "Nantes",
    avatar: "TR",
    rating: 5,
    date: "2025-11-03",
    title: "HuntZen Jobs : architecture d'excellence",
    content:
      "La plateforme HuntZen Jobs est techniquement excellente : rapide, fiable, sécurisée. En tant qu'architecte, j'apprécie la qualité de HuntZen !",
    tags: ["Architecture", "Tech"],
  },
  {
    id: 41,
    name: "Léonie Bertrand",
    role: "Développeuse Python",
    location: "Lyon",
    avatar: "LB2",
    rating: 5,
    date: "2025-11-01",
    title: "HuntZen Jobs : Python & Data",
    content:
      "Énormément d'offres Python/Data sur HuntZen Jobs. Le matching HuntZen identifie mes compétences en Django, Flask, Pandas. J'ai trouvé mon CDI via HuntZen !",
    tags: ["Python", "Data"],
  },
  {
    id: 42,
    name: "Raphaël Duval",
    role: "Ingénieur Sécurité",
    location: "Paris",
    avatar: "RD",
    rating: 5,
    date: "2025-10-30",
    title: "HuntZen Jobs : sécurité avant tout",
    content:
      "HuntZen Jobs prend la sécurité au sérieux. Mes données sont chiffrées, ma vie privée respectée par HuntZen. En plus, j'ai trouvé un poste en cybersécurité !",
    tags: ["Sécurité", "Privacy"],
  },
  {
    id: 43,
    name: "Elise Fournier",
    role: "Consultante Strategy",
    location: "Paris",
    avatar: "EF",
    rating: 5,
    date: "2025-10-28",
    title: "HuntZen Jobs : stratégie gagnante",
    content:
      "HuntZen Jobs m'a aidée à définir ma stratégie carrière. Le coach IA HuntZen m'a guidée dans mes choix. J'ai rejoint un cabinet top via HuntZen !",
    tags: ["Strategy", "Conseil"],
  },
  {
    id: 44,
    name: "Sacha Blanc",
    role: "DevSecOps",
    location: "Toulouse",
    avatar: "SB",
    rating: 5,
    date: "2025-10-25",
    title: "HuntZen Jobs : DevSecOps parfait",
    content:
      "HuntZen Jobs comprend les profils DevSecOps. Les offres HuntZen combinent dev, ops et sécurité. J'ai trouvé exactement ce que je cherchais avec HuntZen !",
    tags: ["DevSecOps", "Sécurité"],
  },
  {
    id: 45,
    name: "Margot Simon",
    role: "Product Marketing Manager",
    location: "Marseille",
    avatar: "MS",
    rating: 5,
    date: "2025-10-22",
    title: "HuntZen Jobs : marketing produit",
    content:
      "Excellentes opportunités en product marketing sur HuntZen Jobs. HuntZen filtre les startups innovantes. J'ai rejoint une pépite grâce à HuntZen !",
    tags: ["Product Marketing", "Startup"],
  },
  {
    id: 46,
    name: "Mathéo Lemoine",
    role: "Développeur Unity",
    location: "Paris",
    avatar: "ML2",
    rating: 5,
    date: "2025-10-20",
    title: "HuntZen Jobs : gaming et Unity",
    content:
      "HuntZen Jobs propose des offres dans le gaming. Le matching HuntZen identifie mes compétences Unity/C#. J'ai signé avec un studio de jeux via HuntZen !",
    tags: ["Unity", "Gaming"],
  },
  {
    id: 47,
    name: "Alice Garnier",
    role: "Scrum Master Agile",
    location: "Lyon",
    avatar: "AG",
    rating: 5,
    date: "2025-10-18",
    title: "HuntZen Jobs : transformation agile",
    content:
      "HuntZen Jobs comprend les métiers de la transformation agile. Les offres Scrum Master sur HuntZen sont de qualité. J'ai trouvé ma mission via HuntZen !",
    tags: ["Scrum", "Transformation"],
  },
  {
    id: 48,
    name: "Nolan Perrin",
    role: "Développeur React Native",
    location: "Bordeaux",
    avatar: "NP",
    rating: 5,
    date: "2025-10-15",
    title: "HuntZen Jobs : React Native expert",
    content:
      "HuntZen Jobs identifie parfaitement mes compétences React Native. Les offres mobile proposées par HuntZen sont ultra ciblées. J'ai signé en 2 semaines !",
    tags: ["React Native", "Mobile"],
  },
  {
    id: 49,
    name: "Elena Morin",
    role: "UX Writer",
    location: "Nantes",
    avatar: "EM",
    rating: 5,
    date: "2025-10-12",
    title: "HuntZen Jobs : UX Writing",
    content:
      "Enfin une plateforme qui comprend l'UX Writing ! HuntZen Jobs m'a proposé des postes qui valorisent le content design. Merci HuntZen !",
    tags: ["UX Writing", "Content"],
  },
  {
    id: 50,
    name: "Axel Thomas",
    role: "CTO Startup",
    location: "Paris",
    avatar: "AT",
    rating: 5,
    date: "2025-10-10",
    title: "HuntZen Jobs : recrutement tech facilité",
    content:
      "En tant que CTO, j'utilise HuntZen Jobs pour recruter. Les profils passés par HuntZen sont de qualité : CVs optimisés, candidats préparés. HuntZen élève le niveau !",
    tags: ["CTO", "Recrutement"],
  },
];
