-- Registre durable des campagnes email et preuve de consentement marketing.
-- Cette migration ne déclenche aucun envoi.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS newsletter_consent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS newsletter_consent_source TEXT,
  ADD COLUMN IF NOT EXISTS newsletter_consent_version TEXT,
  ADD COLUMN IF NOT EXISTS newsletter_unsubscribed_at TIMESTAMPTZ;

UPDATE public.profiles
SET
  newsletter_consent_source = COALESCE(
    newsletter_consent_source,
    'legacy_profile_setting_unknown_date'
  ),
  newsletter_consent_version = COALESCE(newsletter_consent_version, 'legacy-v1'),
  newsletter_unsubscribed_at = NULL
WHERE newsletter_subscribed IS TRUE;

CREATE TABLE IF NOT EXISTS public.email_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_type TEXT NOT NULL CHECK (
    campaign_type IN ('service-update', 'marketing-reactivation')
  ),
  template_version TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (
    status IN ('draft', 'ready', 'running', 'completed', 'failed', 'cancelled')
  ),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  audience_total INTEGER NOT NULL DEFAULT 0 CHECK (audience_total >= 0),
  sent_count INTEGER NOT NULL DEFAULT 0 CHECK (sent_count >= 0),
  failed_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
  skipped_count INTEGER NOT NULL DEFAULT 0 CHECK (skipped_count >= 0),
  audience_frozen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.email_campaign_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id UUID NOT NULL REFERENCES public.email_campaigns(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email_hash TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'en',
  batch_number INTEGER NOT NULL CHECK (batch_number >= 1),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'sending', 'sent', 'failed', 'skipped', 'needs_review')
  ),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  resend_email_id TEXT,
  error_code TEXT,
  claimed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMPTZ,
  UNIQUE (campaign_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_email_campaign_deliveries_claim
  ON public.email_campaign_deliveries (campaign_id, status, batch_number, id);

ALTER TABLE public.email_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_campaign_deliveries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.email_campaigns FROM anon, authenticated;
REVOKE ALL ON TABLE public.email_campaign_deliveries FROM anon, authenticated;
GRANT ALL ON TABLE public.email_campaigns TO service_role;
GRANT ALL ON TABLE public.email_campaign_deliveries TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.email_campaign_deliveries_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.freeze_email_campaign(
  p_campaign_id UUID,
  p_campaign_type TEXT,
  p_template_version TEXT,
  p_created_by UUID,
  p_confirmed_total INTEGER
)
RETURNS SETOF public.email_campaigns
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_campaign public.email_campaigns%ROWTYPE;
  v_actual_total INTEGER;
BEGIN
  IF p_campaign_type NOT IN ('service-update', 'marketing-reactivation') THEN
    RAISE EXCEPTION 'Unknown campaign type';
  END IF;
  IF p_confirmed_total < 0 THEN
    RAISE EXCEPTION 'Invalid confirmed total';
  END IF;

  INSERT INTO public.email_campaigns (
    id, campaign_type, template_version, status, created_by
  ) VALUES (
    p_campaign_id, p_campaign_type, p_template_version, 'draft', p_created_by
  ) ON CONFLICT (id) DO NOTHING;

  SELECT * INTO v_campaign
  FROM public.email_campaigns
  WHERE id = p_campaign_id
  FOR UPDATE;

  IF v_campaign.campaign_type <> p_campaign_type THEN
    RAISE EXCEPTION 'Campaign type mismatch';
  END IF;
  IF v_campaign.audience_frozen_at IS NOT NULL THEN
    IF v_campaign.audience_total <> p_confirmed_total THEN
      RAISE EXCEPTION 'Confirmed total mismatch';
    END IF;
    RETURN NEXT v_campaign;
    RETURN;
  END IF;
  IF v_campaign.status <> 'draft' THEN
    RAISE EXCEPTION 'Campaign cannot be frozen';
  END IF;

  DELETE FROM public.email_campaign_deliveries
  WHERE campaign_id = p_campaign_id;

  INSERT INTO public.email_campaign_deliveries (
    campaign_id, user_id, email_hash, language, batch_number
  )
  SELECT
    p_campaign_id,
    eligible.id,
    ENCODE(DIGEST(LOWER(BTRIM(eligible.email)), 'sha256'), 'hex'),
    COALESCE(eligible.preferred_language, 'en'),
    ((ROW_NUMBER() OVER (ORDER BY eligible.id) - 1) / 100 + 1)::INTEGER
  FROM public.profiles AS eligible
  WHERE eligible.status = 'active'
    AND NULLIF(BTRIM(eligible.email), '') IS NOT NULL
    AND (
      p_campaign_type = 'service-update'
      OR (
        eligible.newsletter_subscribed IS TRUE
        AND eligible.newsletter_consent_at IS NOT NULL
        AND eligible.newsletter_unsubscribed_at IS NULL
      )
    )
  ORDER BY eligible.id;

  GET DIAGNOSTICS v_actual_total = ROW_COUNT;
  IF v_actual_total <> p_confirmed_total THEN
    RAISE EXCEPTION 'Confirmed total mismatch';
  END IF;

  UPDATE public.email_campaigns
  SET
    audience_total = v_actual_total,
    audience_frozen_at = NOW(),
    status = 'ready',
    updated_at = NOW()
  WHERE id = p_campaign_id
  RETURNING * INTO v_campaign;

  RETURN NEXT v_campaign;
END;
$$;

REVOKE ALL ON FUNCTION public.freeze_email_campaign(
  UUID, TEXT, TEXT, UUID, INTEGER
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.freeze_email_campaign(
  UUID, TEXT, TEXT, UUID, INTEGER
) TO service_role;

CREATE OR REPLACE FUNCTION public.claim_email_campaign_deliveries(
  p_campaign_id UUID,
  p_limit INTEGER DEFAULT 100
)
RETURNS TABLE (
  id BIGINT,
  user_id UUID,
  language TEXT,
  batch_number INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_batch_number INTEGER;
BEGIN
  IF p_limit < 1 OR p_limit > 100 THEN
    RAISE EXCEPTION 'p_limit must be between 1 and 100';
  END IF;

  PERFORM 1
  FROM public.email_campaigns AS campaign
  WHERE campaign.id = p_campaign_id
    AND campaign.status = 'running'
  FOR UPDATE SKIP LOCKED;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT MIN(delivery.batch_number)
  INTO v_batch_number
  FROM public.email_campaign_deliveries AS delivery
  WHERE delivery.campaign_id = p_campaign_id
    AND delivery.status = 'pending';

  IF v_batch_number IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  UPDATE public.email_campaign_deliveries AS delivery
  SET
    status = 'sending',
    attempt_count = delivery.attempt_count + 1,
    claimed_at = NOW(),
    updated_at = NOW()
  WHERE delivery.campaign_id = p_campaign_id
    AND delivery.batch_number = v_batch_number
    AND delivery.status = 'pending'
  RETURNING
    delivery.id,
    delivery.user_id,
    delivery.language,
    delivery.batch_number;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_email_campaign_deliveries(UUID, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_email_campaign_deliveries(UUID, INTEGER)
  TO service_role;

REVOKE UPDATE (newsletter_subscribed) ON public.profiles FROM authenticated;

CREATE OR REPLACE FUNCTION public.set_newsletter_preference(
  p_subscribed BOOLEAN
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_rows_updated INTEGER;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  UPDATE public.profiles
  SET
    newsletter_subscribed = p_subscribed,
    newsletter_consent_at = CASE
      WHEN p_subscribed THEN NOW()
      ELSE newsletter_consent_at
    END,
    newsletter_consent_source = CASE
      WHEN p_subscribed THEN 'profile_settings'
      ELSE newsletter_consent_source
    END,
    newsletter_consent_version = CASE
      WHEN p_subscribed THEN '2026-09-v1'
      ELSE newsletter_consent_version
    END,
    newsletter_unsubscribed_at = CASE
      WHEN p_subscribed THEN NULL
      ELSE COALESCE(newsletter_unsubscribed_at, NOW())
    END,
    updated_at = NOW()
  WHERE id = v_user_id;

  GET DIAGNOSTICS v_rows_updated = ROW_COUNT;
  RETURN v_rows_updated = 1;
END;
$$;

REVOKE ALL ON FUNCTION public.set_newsletter_preference(BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_newsletter_preference(BOOLEAN) TO authenticated;

CREATE OR REPLACE FUNCTION public.set_newsletter_preference_for_user(
  p_user_id UUID,
  p_subscribed BOOLEAN
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_rows_updated INTEGER;
BEGIN
  UPDATE public.profiles
  SET
    newsletter_subscribed = p_subscribed,
    newsletter_consent_at = CASE
      WHEN p_subscribed THEN NOW()
      ELSE newsletter_consent_at
    END,
    newsletter_consent_source = CASE
      WHEN p_subscribed THEN 'email_preferences_link'
      ELSE newsletter_consent_source
    END,
    newsletter_consent_version = CASE
      WHEN p_subscribed THEN '2026-09-v1'
      ELSE newsletter_consent_version
    END,
    newsletter_unsubscribed_at = CASE
      WHEN p_subscribed THEN NULL
      ELSE COALESCE(newsletter_unsubscribed_at, NOW())
    END,
    updated_at = NOW()
  WHERE id = p_user_id;

  GET DIAGNOSTICS v_rows_updated = ROW_COUNT;
  RETURN v_rows_updated = 1;
END;
$$;

REVOKE ALL ON FUNCTION public.set_newsletter_preference_for_user(UUID, BOOLEAN)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_newsletter_preference_for_user(UUID, BOOLEAN)
  TO service_role;

COMMENT ON TABLE public.email_campaigns IS
  'Registre des campagnes email avec type et version de modèle immuables.';
COMMENT ON TABLE public.email_campaign_deliveries IS
  'Audience figée et état individuel des envois, sans adresse email en clair.';
COMMENT ON FUNCTION public.freeze_email_campaign(UUID, TEXT, TEXT, UUID, INTEGER) IS
  'Fige transactionnellement une audience confirmée et ses lots stables.';
COMMENT ON FUNCTION public.claim_email_campaign_deliveries(UUID, INTEGER) IS
  'Réserve un lot figé au plus une fois. Un lot ambigu exige une revue manuelle.';
COMMENT ON FUNCTION public.set_newsletter_preference(BOOLEAN) IS
  'Met à jour atomiquement la préférence newsletter de l utilisateur authentifié.';
COMMENT ON FUNCTION public.set_newsletter_preference_for_user(UUID, BOOLEAN) IS
  'Met à jour une préférence par lien signé via le seul rôle de service.';

-- Rollback manuel, uniquement si aucune campagne ne doit être conservée :
-- DROP FUNCTION public.claim_email_campaign_deliveries(UUID, INTEGER);
-- DROP FUNCTION public.freeze_email_campaign(UUID, TEXT, TEXT, UUID, INTEGER);
-- DROP FUNCTION public.set_newsletter_preference(BOOLEAN);
-- DROP FUNCTION public.set_newsletter_preference_for_user(UUID, BOOLEAN);
-- DROP TABLE public.email_campaign_deliveries;
-- DROP TABLE public.email_campaigns;
-- ALTER TABLE public.profiles DROP COLUMN newsletter_unsubscribed_at,
--   DROP COLUMN newsletter_consent_version,
--   DROP COLUMN newsletter_consent_source,
--   DROP COLUMN newsletter_consent_at;
