-- Migration: Create Storage buckets for generated CV and cover letter PDFs
-- These buckets store adapted CVs and cover letters generated by the AI.

-- Create private buckets (authenticated access only via RLS policies)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  (
    'cvs-adaptes',
    'cvs-adaptes',
    false,
    10485760, -- 10 MB
    ARRAY['application/pdf']
  ),
  (
    'lettres-motivation',
    'lettres-motivation',
    false,
    10485760, -- 10 MB
    ARRAY['application/pdf']
  )
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- RLS Policies: cvs-adaptes
-- ============================================================

-- Users can upload only to their own folder
CREATE POLICY "Users upload own CVs"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'cvs-adaptes'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Users can read only their own files
CREATE POLICY "Users read own CVs"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'cvs-adaptes'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Users can delete only their own files
CREATE POLICY "Users delete own CVs"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'cvs-adaptes'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- ============================================================
-- RLS Policies: lettres-motivation
-- ============================================================

CREATE POLICY "Users upload own LMs"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'lettres-motivation'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users read own LMs"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'lettres-motivation'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users delete own LMs"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'lettres-motivation'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
