/**
 * Export CV Analysis Results to PDF
 * Uses @react-pdf/renderer for PDF generation
 */

import { pdf } from "@react-pdf/renderer";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { CVAnalysisResult } from "@/hooks/use-cv-history";

// PDF Styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 20,
    borderBottom: "2px solid #2563eb",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1e40af",
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: "#6b7280",
  },
  section: {
    marginTop: 15,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 10,
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: 5,
  },
  scoreContainer: {
    backgroundColor: "#eff6ff",
    padding: 15,
    borderRadius: 8,
    marginBottom: 15,
  },
  scoreText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#2563eb",
    textAlign: "center",
  },
  scoreLabel: {
    fontSize: 12,
    color: "#6b7280",
    textAlign: "center",
    marginTop: 5,
  },
  breakdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  breakdownLabel: {
    fontSize: 11,
    color: "#374151",
  },
  breakdownValue: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#2563eb",
  },
  listItem: {
    fontSize: 10,
    color: "#4b5563",
    marginBottom: 5,
    paddingLeft: 10,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#9ca3af",
    borderTop: "1px solid #e5e7eb",
    paddingTop: 10,
  },
});

// PDF labels by locale
const PDF_LABELS: Record<string, Record<string, string>> = {
  fr: {
    title: "Analyse de CV - R\u00e9sultats",
    generatedOn: "G\u00e9n\u00e9r\u00e9 le",
    overallScore: "Score Global",
    breakdown: "D\u00e9tails du Score",
    strengths: "Points Forts",
    weaknesses: "Points \u00e0 Am\u00e9liorer",
    suggestions: "Recommandations",
    footer:
      "G\u00e9n\u00e9r\u00e9 par HuntZen - Plateforme d\u2019assistance \u00e0 la recherche d\u2019emploi",
  },
  en: {
    title: "CV Analysis - Results",
    generatedOn: "Generated on",
    overallScore: "Overall Score",
    breakdown: "Score Breakdown",
    strengths: "Strengths",
    weaknesses: "Areas for Improvement",
    suggestions: "Recommendations",
    footer: "Generated by HuntZen - AI-powered job search assistant",
  },
};

function getPdfLabels(locale?: string): Record<string, string> {
  return PDF_LABELS[locale || "fr"] || PDF_LABELS.fr;
}

// PDF Document Component
const CVAnalysisPDFDocument = ({
  result,
  locale,
}: {
  result: CVAnalysisResult;
  locale?: string;
}) => {
  const labels = getPdfLabels(locale);
  const dateLocale = locale === "en" ? "en-US" : "fr-FR";
  const analyzedDate =
    result.analyzedAt instanceof Date
      ? result.analyzedAt.toLocaleDateString(dateLocale)
      : new Date(result.analyzedAt).toLocaleDateString(dateLocale);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>{labels.title}</Text>
          <Text style={styles.subtitle}>
            {result.fileName} {"\u2014"} {labels.generatedOn} {analyzedDate}
          </Text>
        </View>

        {/* Overall Score */}
        <View style={styles.scoreContainer}>
          <Text style={styles.scoreText}>{result.score}/100</Text>
          <Text style={styles.scoreLabel}>{labels.overallScore}</Text>
        </View>

        {/* Score Breakdown */}
        {result.breakdown && result.breakdown.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{labels.breakdown}</Text>
            {result.breakdown.map((item, index) => (
              <View key={index} style={styles.breakdown}>
                <Text style={styles.breakdownLabel}>{item.label}</Text>
                <Text style={styles.breakdownValue}>
                  {item.value}/{item.max}
                </Text>
              </View>
            ))}
          </View>
        )}

        {/* Strengths */}
        {result.strengths && result.strengths.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{labels.strengths}</Text>
            {result.strengths.map((strength, index) => (
              <Text key={index} style={styles.listItem}>
                {"\u2022"} {strength}
              </Text>
            ))}
          </View>
        )}

        {/* Weaknesses */}
        {result.weaknesses && result.weaknesses.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{labels.weaknesses}</Text>
            {result.weaknesses.map((weakness, index) => (
              <Text key={index} style={styles.listItem}>
                {"\u2022"} {weakness}
              </Text>
            ))}
          </View>
        )}

        {/* Suggestions */}
        {result.suggestions && result.suggestions.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{labels.suggestions}</Text>
            {result.suggestions.map((suggestion, index) => (
              <Text key={index} style={styles.listItem}>
                {"\u2022"} {suggestion.text}
              </Text>
            ))}
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>{labels.footer}</Text>
          <Text>huntzenjobs.com</Text>
        </View>
      </Page>
    </Document>
  );
};

/**
 * Export CV analysis results to PDF file
 * @param result - CV analysis result object
 * @param fileName - Optional custom filename (default: cv-analysis-{date}.pdf)
 * @param locale - Locale for PDF labels (default: "fr")
 */
export async function exportCVAnalysisToPDF(
  result: CVAnalysisResult,
  fileName?: string,
  locale?: string,
): Promise<void> {
  try {
    const blob = await pdf(
      <CVAnalysisPDFDocument result={result} locale={locale} />,
    ).toBlob();

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download =
      fileName || `cv-analysis-${new Date().toISOString().split("T")[0]}.pdf`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Failed to export PDF:", error);
    throw new Error("Échec de l'export PDF");
  }
}
